import type { BombChallenge } from "./bomb-types";

/**
 * Banco de desafios do "Bomba-Relógio".
 *
 * O desafio é lido em voz alta e cada pessoa da roda precisa dar uma resposta NOVA
 * antes de passar o celular. Logo, o critério número um é o `pool`: um grupo de 8
 * pessoas gera 20+ respostas no mesmo desafio, então "Diga um planeta" não serve e
 * "Diga algo relacionado ao espaço" serve.
 *
 * Critérios:
 * - 10 categorias x 18 desafios = 180, ids sequenciais por prefixo de categoria.
 * - Frase curta, inteira, no imperativo ("Diga…", com "Cite…"/"Fale…" de tempero).
 *   A resposta tem que sair em 2 ou 3 segundos: nada de cálculo ou memória longa.
 * - `pool` é estimativa honesta de respostas distintas: `alto` = dezenas,
 *   `medio` = ~15, `baixo` = menos de 10. Cada categoria tem >= 12 `alto` e no
 *   máximo 2 `baixo` (só onde o desafio é divertido o bastante para compensar).
 * - Dificuldade: ~8 `facil`, ~7 `medio`, ~3 `dificil` por categoria. Exceção:
 *   `Caos` é quase todo `facil` e 100% `alto`, porque são perguntas abertas.
 * - Segurança: nada de saúde física ou mental, aparência, raça, etnia, religião,
 *   orientação sexual, identidade de gênero, crimes, violência, morte, drogas,
 *   sexo explícito ou política partidária. Álcool só em `Festa`, de forma leve.
 * - Nenhum enunciado cita pessoa real ou marca específica (o jogador pode
 *   responder marcas; a pergunta não entrega nenhuma).
 */
export const CHALLENGES: BombChallenge[] = [
  // Conhecimentos gerais — mundo, natureza, objetos, profissões
  {
    id: "ger-001",
    category: "Conhecimentos gerais",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma cor.",
  },
  {
    id: "ger-002",
    category: "Conhecimentos gerais",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um animal de quatro patas.",
  },
  {
    id: "ger-003",
    category: "Conhecimentos gerais",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma profissão.",
  },
  {
    id: "ger-004",
    category: "Conhecimentos gerais",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que existe numa cozinha.",
  },
  {
    id: "ger-005",
    category: "Conhecimentos gerais",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma parte do corpo.",
  },
  {
    id: "ger-006",
    category: "Conhecimentos gerais",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que voa.",
  },
  {
    id: "ger-007",
    category: "Conhecimentos gerais",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo feito de madeira.",
  },
  {
    id: "ger-008",
    category: "Conhecimentos gerais",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma peça de roupa.",
  },
  {
    id: "ger-009",
    category: "Conhecimentos gerais",
    difficulty: "medio",
    pool: "alto",
    text: "Cite algo que se compra na farmácia.",
  },
  {
    id: "ger-010",
    category: "Conhecimentos gerais",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo relacionado ao espaço.",
  },
  {
    id: "ger-011",
    category: "Conhecimentos gerais",
    difficulty: "medio",
    pool: "alto",
    text: "Diga uma marca de carro.",
  },
  {
    id: "ger-012",
    category: "Conhecimentos gerais",
    difficulty: "medio",
    pool: "alto",
    text: "Diga uma ferramenta.",
  },
  {
    id: "ger-013",
    category: "Conhecimentos gerais",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que vive no mar.",
  },
  {
    id: "ger-014",
    category: "Conhecimentos gerais",
    difficulty: "medio",
    pool: "medio",
    text: "Diga um país da América do Sul.",
  },
  {
    id: "ger-015",
    category: "Conhecimentos gerais",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que se usa na cabeça.",
  },
  {
    id: "ger-016",
    category: "Conhecimentos gerais",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga a capital de um estado brasileiro.",
  },
  {
    id: "ger-017",
    category: "Conhecimentos gerais",
    difficulty: "dificil",
    pool: "medio",
    text: "Diga uma árvore.",
  },
  {
    id: "ger-018",
    category: "Conhecimentos gerais",
    difficulty: "dificil",
    pool: "baixo",
    text: "Diga um continente.",
  },

  // Engraçado — desculpas, situações e absurdos do dia a dia
  {
    id: "eng-001",
    category: "Engraçado",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma desculpa para chegar atrasado.",
  },
  {
    id: "eng-002",
    category: "Engraçado",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma desculpa para não ir a uma festa.",
  },
  {
    id: "eng-003",
    category: "Engraçado",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que todo mundo faz escondido.",
  },
  {
    id: "eng-004",
    category: "Engraçado",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que dá vergonha admitir que você gosta.",
  },
  {
    id: "eng-005",
    category: "Engraçado",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um apelido ridículo para um bichinho de estimação.",
  },
  {
    id: "eng-006",
    category: "Engraçado",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que sempre desaparece dentro de casa.",
  },
  {
    id: "eng-007",
    category: "Engraçado",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma mentirinha que todo mundo já contou.",
  },
  {
    id: "eng-008",
    category: "Engraçado",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que é impossível fazer sem fazer careta.",
  },
  {
    id: "eng-009",
    category: "Engraçado",
    difficulty: "medio",
    pool: "alto",
    text: "Diga uma desculpa para sair mais cedo do trabalho.",
  },
  {
    id: "eng-010",
    category: "Engraçado",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que ninguém deveria fazer dentro do elevador.",
  },
  {
    id: "eng-011",
    category: "Engraçado",
    difficulty: "medio",
    pool: "alto",
    text: "Diga um barulho que dá raiva de ouvir.",
  },
  {
    id: "eng-012",
    category: "Engraçado",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo inútil que você guarda em casa.",
  },
  {
    id: "eng-013",
    category: "Engraçado",
    difficulty: "medio",
    pool: "alto",
    text: "Fale uma frase que a sua mãe sempre diz.",
  },
  {
    id: "eng-014",
    category: "Engraçado",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que fica estranho de falar em voz alta.",
  },
  {
    id: "eng-015",
    category: "Engraçado",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que você faz quando a internet cai.",
  },
  {
    id: "eng-016",
    category: "Engraçado",
    difficulty: "dificil",
    pool: "alto",
    text: "Cite uma invenção que ninguém pediu.",
  },
  {
    id: "eng-017",
    category: "Engraçado",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga algo que seria péssimo ter dentro do bolso.",
  },
  {
    id: "eng-018",
    category: "Engraçado",
    difficulty: "dificil",
    pool: "medio",
    text: "Diga uma tarefa de casa que todo mundo odeia.",
  },

  // Filmes e séries — personagens, títulos e clichês
  {
    id: "fil-001",
    category: "Filmes e séries",
    difficulty: "facil",
    pool: "alto",
    text: "Diga o nome de um filme.",
  },
  {
    id: "fil-002",
    category: "Filmes e séries",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um personagem de desenho animado.",
  },
  {
    id: "fil-003",
    category: "Filmes e séries",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um filme que você já assistiu mais de uma vez.",
  },
  {
    id: "fil-004",
    category: "Filmes e séries",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um super-herói.",
  },
  {
    id: "fil-005",
    category: "Filmes e séries",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma série que você terminou.",
  },
  {
    id: "fil-006",
    category: "Filmes e séries",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um filme de terror.",
  },
  {
    id: "fil-007",
    category: "Filmes e séries",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um ator ou uma atriz.",
  },
  {
    id: "fil-008",
    category: "Filmes e séries",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um filme que faz chorar.",
  },
  {
    id: "fil-009",
    category: "Filmes e séries",
    difficulty: "medio",
    pool: "alto",
    text: "Diga um vilão de filme.",
  },
  {
    id: "fil-010",
    category: "Filmes e séries",
    difficulty: "medio",
    pool: "medio",
    text: "Diga uma novela brasileira.",
  },
  {
    id: "fil-011",
    category: "Filmes e séries",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que sempre acontece em filme de ação.",
  },
  {
    id: "fil-012",
    category: "Filmes e séries",
    difficulty: "medio",
    pool: "alto",
    text: "Diga um filme de animação.",
  },
  {
    id: "fil-013",
    category: "Filmes e séries",
    difficulty: "medio",
    pool: "alto",
    text: "Cite uma fala famosa de filme.",
  },
  {
    id: "fil-014",
    category: "Filmes e séries",
    difficulty: "medio",
    pool: "alto",
    text: "Diga um filme que saiu de um livro.",
  },
  {
    id: "fil-015",
    category: "Filmes e séries",
    difficulty: "medio",
    pool: "medio",
    text: "Diga uma série de comédia.",
  },
  {
    id: "fil-016",
    category: "Filmes e séries",
    difficulty: "dificil",
    pool: "alto",
    text: "Cite um filme lançado antes de você nascer.",
  },
  {
    id: "fil-017",
    category: "Filmes e séries",
    difficulty: "dificil",
    pool: "medio",
    text: "Diga um diretor de cinema.",
  },
  {
    id: "fil-018",
    category: "Filmes e séries",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga um filme que ganhou continuação.",
  },

  // Esportes — futebol e o resto, com termos e equipamento
  {
    id: "esp-001",
    category: "Esportes",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um esporte.",
  },
  {
    id: "esp-002",
    category: "Esportes",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um time de futebol brasileiro.",
  },
  {
    id: "esp-003",
    category: "Esportes",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que se usa para praticar um esporte.",
  },
  {
    id: "esp-004",
    category: "Esportes",
    difficulty: "facil",
    pool: "medio",
    text: "Diga um esporte que usa bola.",
  },
  {
    id: "esp-005",
    category: "Esportes",
    difficulty: "facil",
    pool: "baixo",
    text: "Diga uma posição do futebol.",
  },
  {
    id: "esp-006",
    category: "Esportes",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um jogador de futebol.",
  },
  {
    id: "esp-007",
    category: "Esportes",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que o juiz faz durante o jogo.",
  },
  {
    id: "esp-008",
    category: "Esportes",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um esporte olímpico.",
  },
  {
    id: "esp-009",
    category: "Esportes",
    difficulty: "medio",
    pool: "alto",
    text: "Diga um estádio de futebol.",
  },
  {
    id: "esp-010",
    category: "Esportes",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que se grita na arquibancada.",
  },
  {
    id: "esp-011",
    category: "Esportes",
    difficulty: "medio",
    pool: "medio",
    text: "Diga um esporte que se pratica na água.",
  },
  {
    id: "esp-012",
    category: "Esportes",
    difficulty: "medio",
    pool: "alto",
    text: "Diga uma seleção que já jogou uma Copa.",
  },
  {
    id: "esp-013",
    category: "Esportes",
    difficulty: "medio",
    pool: "alto",
    text: "Cite um termo do vôlei.",
  },
  {
    id: "esp-014",
    category: "Esportes",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que existe numa academia.",
  },
  {
    id: "esp-015",
    category: "Esportes",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que todo torcedor já fez vendo um jogo.",
  },
  {
    id: "esp-016",
    category: "Esportes",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga um esporte que não usa bola.",
  },
  {
    id: "esp-017",
    category: "Esportes",
    difficulty: "dificil",
    pool: "medio",
    text: "Diga um esporte radical.",
  },
  {
    id: "esp-018",
    category: "Esportes",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga um campeonato de futebol.",
  },

  // Música — gêneros, instrumentos, show e karaokê
  {
    id: "mus-001",
    category: "Música",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um gênero musical.",
  },
  {
    id: "mus-002",
    category: "Música",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um instrumento musical.",
  },
  {
    id: "mus-003",
    category: "Música",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma música que todo mundo sabe cantar.",
  },
  {
    id: "mus-004",
    category: "Música",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um cantor ou uma cantora.",
  },
  {
    id: "mus-005",
    category: "Música",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma banda.",
  },
  {
    id: "mus-006",
    category: "Música",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma música boa de karaokê.",
  },
  {
    id: "mus-007",
    category: "Música",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que tem em todo show.",
  },
  {
    id: "mus-008",
    category: "Música",
    difficulty: "facil",
    pool: "medio",
    text: "Diga uma música de festa junina.",
  },
  {
    id: "mus-009",
    category: "Música",
    difficulty: "medio",
    pool: "alto",
    text: "Diga uma música que grudou na sua cabeça.",
  },
  {
    id: "mus-010",
    category: "Música",
    difficulty: "medio",
    pool: "alto",
    text: "Fale um verso de qualquer música.",
  },
  {
    id: "mus-011",
    category: "Música",
    difficulty: "medio",
    pool: "medio",
    text: "Diga uma música que toca em todo casamento.",
  },
  {
    id: "mus-012",
    category: "Música",
    difficulty: "medio",
    pool: "medio",
    text: "Diga um instrumento de percussão.",
  },
  {
    id: "mus-013",
    category: "Música",
    difficulty: "medio",
    pool: "alto",
    text: "Diga uma música de Carnaval.",
  },
  {
    id: "mus-014",
    category: "Música",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que se leva para um festival.",
  },
  {
    id: "mus-015",
    category: "Música",
    difficulty: "medio",
    pool: "medio",
    text: "Diga uma dupla sertaneja.",
  },
  {
    id: "mus-016",
    category: "Música",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga uma música em inglês.",
  },
  {
    id: "mus-017",
    category: "Música",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga uma música que te lembra a infância.",
  },
  {
    id: "mus-018",
    category: "Música",
    difficulty: "dificil",
    pool: "baixo",
    text: "Diga um ritmo típico do Nordeste.",
  },

  // Comida — pratos, bebidas, ingredientes e cozinha
  {
    id: "com-001",
    category: "Comida",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma fruta.",
  },
  {
    id: "com-002",
    category: "Comida",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que se come no café da manhã.",
  },
  {
    id: "com-003",
    category: "Comida",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um sabor de sorvete.",
  },
  {
    id: "com-004",
    category: "Comida",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que vai na pizza.",
  },
  {
    id: "com-005",
    category: "Comida",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma bebida.",
  },
  {
    id: "com-006",
    category: "Comida",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um doce.",
  },
  {
    id: "com-007",
    category: "Comida",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que se come com a mão.",
  },
  {
    id: "com-008",
    category: "Comida",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um tempero.",
  },
  {
    id: "com-009",
    category: "Comida",
    difficulty: "medio",
    pool: "alto",
    text: "Diga um prato que leva arroz.",
  },
  {
    id: "com-010",
    category: "Comida",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que se vende na padaria.",
  },
  {
    id: "com-011",
    category: "Comida",
    difficulty: "medio",
    pool: "medio",
    text: "Cite um prato de festa junina.",
  },
  {
    id: "com-012",
    category: "Comida",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que estraga rápido na geladeira.",
  },
  {
    id: "com-013",
    category: "Comida",
    difficulty: "medio",
    pool: "medio",
    text: "Diga um recheio de pastel.",
  },
  {
    id: "com-014",
    category: "Comida",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que se come na praia.",
  },
  {
    id: "com-015",
    category: "Comida",
    difficulty: "medio",
    pool: "alto",
    text: "Diga um legume ou uma verdura.",
  },
  {
    id: "com-016",
    category: "Comida",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga um prato típico de alguma região do Brasil.",
  },
  {
    id: "com-017",
    category: "Comida",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga um ingrediente de bolo.",
  },
  {
    id: "com-018",
    category: "Comida",
    difficulty: "dificil",
    pool: "alto",
    text: "Cite uma comida que você só come na casa da sua avó.",
  },

  // Lugares — cidades, países, tipos de lugar e cômodos
  {
    id: "lug-001",
    category: "Lugares",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um país.",
  },
  {
    id: "lug-002",
    category: "Lugares",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma cidade brasileira.",
  },
  {
    id: "lug-003",
    category: "Lugares",
    difficulty: "facil",
    pool: "baixo",
    text: "Diga um cômodo da casa.",
  },
  {
    id: "lug-004",
    category: "Lugares",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um lugar onde tem muita gente.",
  },
  {
    id: "lug-005",
    category: "Lugares",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um lugar que se visita numa viagem.",
  },
  {
    id: "lug-006",
    category: "Lugares",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um estado brasileiro.",
  },
  {
    id: "lug-007",
    category: "Lugares",
    difficulty: "facil",
    pool: "medio",
    text: "Diga um lugar onde é proibido falar alto.",
  },
  {
    id: "lug-008",
    category: "Lugares",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma cidade de praia.",
  },
  {
    id: "lug-009",
    category: "Lugares",
    difficulty: "medio",
    pool: "medio",
    text: "Diga um país da Europa.",
  },
  {
    id: "lug-010",
    category: "Lugares",
    difficulty: "medio",
    pool: "alto",
    text: "Diga um lugar que abre de madrugada.",
  },
  {
    id: "lug-011",
    category: "Lugares",
    difficulty: "medio",
    pool: "alto",
    text: "Diga um tipo de loja de shopping.",
  },
  {
    id: "lug-012",
    category: "Lugares",
    difficulty: "medio",
    pool: "alto",
    text: "Diga um lugar onde sempre tem fila.",
  },
  {
    id: "lug-013",
    category: "Lugares",
    difficulty: "medio",
    pool: "alto",
    text: "Cite um ponto turístico.",
  },
  {
    id: "lug-014",
    category: "Lugares",
    difficulty: "medio",
    pool: "alto",
    text: "Diga um lugar que dá medo à noite.",
  },
  {
    id: "lug-015",
    category: "Lugares",
    difficulty: "medio",
    pool: "alto",
    text: "Diga a capital de outro país.",
  },
  {
    id: "lug-016",
    category: "Lugares",
    difficulty: "dificil",
    pool: "baixo",
    text: "Diga um país que faz fronteira com o Brasil.",
  },
  {
    id: "lug-017",
    category: "Lugares",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga uma ilha.",
  },
  {
    id: "lug-018",
    category: "Lugares",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga um lugar que existe em toda cidade pequena.",
  },

  // Games — videogame, tabuleiro e brincadeira
  {
    id: "gam-001",
    category: "Games",
    difficulty: "facil",
    pool: "alto",
    text: "Diga o nome de um jogo de videogame.",
  },
  {
    id: "gam-002",
    category: "Games",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma brincadeira de criança.",
  },
  {
    id: "gam-003",
    category: "Games",
    difficulty: "facil",
    pool: "medio",
    text: "Diga um jogo de tabuleiro.",
  },
  {
    id: "gam-004",
    category: "Games",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um jogo de celular.",
  },
  {
    id: "gam-005",
    category: "Games",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um personagem de videogame.",
  },
  {
    id: "gam-006",
    category: "Games",
    difficulty: "facil",
    pool: "medio",
    text: "Diga um jogo de carta.",
  },
  {
    id: "gam-007",
    category: "Games",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que dá raiva em jogo online.",
  },
  {
    id: "gam-008",
    category: "Games",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um jogo que se joga em dupla.",
  },
  {
    id: "gam-009",
    category: "Games",
    difficulty: "medio",
    pool: "baixo",
    text: "Diga um console de videogame.",
  },
  {
    id: "gam-010",
    category: "Games",
    difficulty: "medio",
    pool: "alto",
    text: "Fale uma palavra que gamer usa.",
  },
  {
    id: "gam-011",
    category: "Games",
    difficulty: "medio",
    pool: "medio",
    text: "Diga um jogo de corrida.",
  },
  {
    id: "gam-012",
    category: "Games",
    difficulty: "medio",
    pool: "alto",
    text: "Diga um jogo que sempre acaba em discussão.",
  },
  {
    id: "gam-013",
    category: "Games",
    difficulty: "medio",
    pool: "alto",
    text: "Diga um jogo que dá para jogar sem nada na mão.",
  },
  {
    id: "gam-014",
    category: "Games",
    difficulty: "medio",
    pool: "medio",
    text: "Diga um jogo de luta.",
  },
  {
    id: "gam-015",
    category: "Games",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que se coleciona dentro de um jogo.",
  },
  {
    id: "gam-016",
    category: "Games",
    difficulty: "dificil",
    pool: "medio",
    text: "Diga um jogo antigo de fliperama.",
  },
  {
    id: "gam-017",
    category: "Games",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga um jogo que você nunca conseguiu terminar.",
  },
  {
    id: "gam-018",
    category: "Games",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga algo que existe em quase todo jogo de videogame.",
  },

  // Festa — rolê, aniversário, churrasco e virada de ano
  {
    id: "fes-001",
    category: "Festa",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que tem em toda festa de aniversário.",
  },
  {
    id: "fes-002",
    category: "Festa",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que se leva para um churrasco.",
  },
  {
    id: "fes-003",
    category: "Festa",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que se faz na virada do ano.",
  },
  {
    id: "fes-004",
    category: "Festa",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um motivo para fazer uma festa.",
  },
  {
    id: "fes-005",
    category: "Festa",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que sempre sobra depois da festa.",
  },
  {
    id: "fes-006",
    category: "Festa",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma fantasia de Carnaval.",
  },
  {
    id: "fes-007",
    category: "Festa",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que estraga uma festa.",
  },
  {
    id: "fes-008",
    category: "Festa",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma bebida de festa.",
  },
  {
    id: "fes-009",
    category: "Festa",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que tem numa festa junina.",
  },
  {
    id: "fes-010",
    category: "Festa",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que só aparece na festa depois da meia-noite.",
  },
  {
    id: "fes-011",
    category: "Festa",
    difficulty: "medio",
    pool: "alto",
    text: "Diga um item de decoração de festa.",
  },
  {
    id: "fes-012",
    category: "Festa",
    difficulty: "medio",
    pool: "alto",
    text: "Diga uma tarefa de quem organiza o rolê.",
  },
  {
    id: "fes-013",
    category: "Festa",
    difficulty: "medio",
    pool: "alto",
    text: "Diga um rolê que não custa nada.",
  },
  {
    id: "fes-014",
    category: "Festa",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que se faz numa festa na piscina.",
  },
  {
    id: "fes-015",
    category: "Festa",
    difficulty: "medio",
    pool: "medio",
    text: "Diga um tipo de festa.",
  },
  {
    id: "fes-016",
    category: "Festa",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga algo que sempre dá errado num churrasco.",
  },
  {
    id: "fes-017",
    category: "Festa",
    difficulty: "dificil",
    pool: "alto",
    text: "Fale uma promessa de ano novo.",
  },
  {
    id: "fes-018",
    category: "Festa",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga algo que todo mundo esquece de levar para a festa.",
  },

  // Caos — perguntas abertas: quase tudo facil e alto
  {
    id: "cao-001",
    category: "Caos",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que você faria se ganhasse na loteria.",
  },
  {
    id: "cao-002",
    category: "Caos",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que você nunca faria por dinheiro.",
  },
  {
    id: "cao-003",
    category: "Caos",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que você levaria para uma ilha deserta.",
  },
  {
    id: "cao-004",
    category: "Caos",
    difficulty: "facil",
    pool: "alto",
    text: "Diga uma superstição.",
  },
  {
    id: "cao-005",
    category: "Caos",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que você faria se ficasse invisível por um dia.",
  },
  {
    id: "cao-006",
    category: "Caos",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um poder que você queria ter.",
  },
  {
    id: "cao-007",
    category: "Caos",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que você faria se o mundo parasse por um dia.",
  },
  {
    id: "cao-008",
    category: "Caos",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que você diria para você mesmo criança.",
  },
  {
    id: "cao-009",
    category: "Caos",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que deveria existir e ainda não existe.",
  },
  {
    id: "cao-010",
    category: "Caos",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que você faria se acordasse gigante.",
  },
  {
    id: "cao-011",
    category: "Caos",
    difficulty: "facil",
    pool: "alto",
    text: "Diga um nome esquisito para uma banda.",
  },
  {
    id: "cao-012",
    category: "Caos",
    difficulty: "facil",
    pool: "alto",
    text: "Diga algo que você faria se pudesse voar.",
  },
  {
    id: "cao-013",
    category: "Caos",
    difficulty: "medio",
    pool: "alto",
    text: "Cite algo que seria péssimo ter em dobro.",
  },
  {
    id: "cao-014",
    category: "Caos",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que você faria se ninguém estivesse olhando.",
  },
  {
    id: "cao-015",
    category: "Caos",
    difficulty: "medio",
    pool: "alto",
    text: "Fale uma pergunta que ninguém sabe responder.",
  },
  {
    id: "cao-016",
    category: "Caos",
    difficulty: "medio",
    pool: "alto",
    text: "Diga algo que você levaria numa viagem no tempo.",
  },
  {
    id: "cao-017",
    category: "Caos",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga uma palavra que não existe.",
  },
  {
    id: "cao-018",
    category: "Caos",
    difficulty: "dificil",
    pool: "alto",
    text: "Diga algo que você explicaria para um alienígena.",
  },
];
