import type { CoupleCard } from './couple-types';

/**
 * Banco de cartas do "Entre Nós" — um casal, um celular, nenhuma pontuação.
 *
 * A régua: uma carta é boa se render trinta minutos de conversa. É ruim se for
 * respondida com uma palavra e um silêncio.
 *
 * Critérios de escrita:
 * - 10 categorias, ids sequenciais de 3 dígitos por prefixo.
 * - `Leve e divertido` é 100% `leve`, `Valores` é 100% `profundo`, `Intimidade`
 *   é 100% `intimidade` (categoria opt-in: o casal marca conscientemente).
 * - 12 cartas de ação, sem `followUps`: são coisas para fazer agora, não perguntas.
 * - Segurança emocional: nada de traumas, término, infidelidade, ciúme, ex-parceiros,
 *   fertilidade, gravidez, doença, saúde mental, morte, luto, dinheiro apertado,
 *   conflito familiar, religião, política, julgamento de aparência ou confissão.
 *   O teste aplicado em cada carta: se a resposta honesta puder magoar quem pergunta
 *   ou humilhar quem responde, a carta não entra. `profundo` pede vulnerabilidade,
 *   mas sempre pelo caminho do que a pessoa quer, valoriza, sente falta ou sonha —
 *   nunca do que a incomoda no outro.
 * - Neutro quanto a gênero, sem "(a)". Não pressupõe casamento, filhos, morar junto
 *   nem dinheiro sobrando: o casal pode estar junto há dois meses.
 * - `followUps` puxam a MESMA conversa mais fundo; nunca trocam de assunto.
 */
export const CARDS: CoupleCard[] = [
  // ─── Nosso relacionamento ────────────────────────────────────────────────
  {
    id: 'rel-001',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'conectar',
    text: 'Em quais momentos você se sente mais querido por mim?',
    followUps: ['O que eu poderia fazer para isso acontecer mais vezes?'],
  },
  {
    id: 'rel-002',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'leve',
    text: 'Qual hábito nosso, desses bobos de todo dia, você não trocaria por nada?',
    followUps: ['Como foi que ele começou?'],
  },
  {
    id: 'rel-003',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'profundo',
    text: 'O que a gente tem hoje que você não imaginava que teria com alguém?',
    followUps: ['Quando foi que você percebeu isso?', 'O que fez a gente chegar aí?'],
  },
  {
    id: 'rel-004',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'conectar',
    text: 'Em que a gente é melhor junto do que separado?',
    followUps: ['Onde isso aparece mais no dia a dia?'],
  },
  {
    id: 'rel-005',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'leve',
    text: 'Se a nossa relação fosse uma música, qual seria?',
    followUps: ['Qual trecho dela mais parece com a gente?'],
  },
  {
    id: 'rel-006',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'conectar',
    text: 'O que eu faço que te dá segurança?',
    followUps: ['Teve algum momento em que você sentiu isso bem forte?'],
  },
  {
    id: 'rel-007',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'profundo',
    text: 'Em que parte da sua vida eu te mudei para melhor?',
    followUps: ['O que mudou na prática depois disso?'],
  },
  {
    id: 'rel-008',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'conectar',
    text: 'O que te faz sentir que a gente está perto, mesmo num dia corrido?',
    followUps: ['Qual foi a última vez que isso aconteceu?'],
  },
  {
    id: 'rel-009',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'leve',
    text: 'Qual apelido ou piada interna nossa é a sua favorita?',
    followUps: ['De onde ela surgiu mesmo?'],
  },
  {
    id: 'rel-010',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'profundo',
    text: 'O que você mais admira no meu jeito de lidar com as coisas?',
    followUps: ['Em que momento você viu isso acontecer?'],
  },
  {
    id: 'rel-011',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'conectar',
    text: 'Qual foi a última vez que eu te surpreendi?',
    followUps: ['O que daquilo te pegou de jeito?'],
  },
  {
    id: 'rel-012',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'conectar',
    text: 'Quando você sente mais orgulho de estar comigo?',
    followUps: ['O que estava rolando na última vez que você sentiu isso?'],
  },
  {
    id: 'rel-013',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'profundo',
    text: 'O que a gente ainda está aprendendo a fazer junto?',
    followUps: ['Como você acha que a gente chega lá?'],
  },
  {
    id: 'rel-014',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'leve',
    text: 'Se alguém fizesse um documentário sobre a gente, qual seria o título?',
    followUps: ['Qual cena entraria logo na abertura?'],
  },
  {
    id: 'rel-015',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'conectar',
    text: 'Qual combinado nosso ninguém de fora entenderia?',
    followUps: ['Quando foi que ele virou regra sem ninguém falar nada?'],
  },
  {
    id: 'rel-016',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'conectar',
    text: 'Do que você sente falta quando a gente passa dias sem tempo um para o outro?',
    followUps: ['Como eu percebo que você está sentindo essa falta?'],
  },
  {
    id: 'rel-017',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'profundo',
    text: 'O que a gente construiu junto que você mais valoriza?',
    followUps: ['O que a gente fez para isso dar certo?'],
  },
  {
    id: 'rel-018',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'leve',
    text: 'Qual tarefa chata fica boa só porque a gente faz junto?',
    followUps: ['Qual delas você faria sozinho sem reclamar?'],
  },
  {
    id: 'rel-019',
    kind: 'pergunta',
    category: 'Nosso relacionamento',
    depth: 'conectar',
    text: 'Que tipo de apoio meu funciona melhor para você: ouvir, resolver ou só ficar do lado?',
    followUps: ['Como eu vou saber qual deles você quer na hora?'],
  },
  {
    id: 'rel-020',
    kind: 'acao',
    category: 'Nosso relacionamento',
    depth: 'conectar',
    text: 'Diga em voz alta três coisas que a gente faz bem junto.',
  },
  {
    id: 'rel-021',
    kind: 'acao',
    category: 'Nosso relacionamento',
    depth: 'leve',
    text: 'Mostre agora uma foto do seu celular que represente a gente.',
  },
  {
    id: 'rel-022',
    kind: 'acao',
    category: 'Nosso relacionamento',
    depth: 'profundo',
    text: 'Diga uma coisa que você admira em mim e quase nunca fala em voz alta.',
  },

  // ─── Nossa história ──────────────────────────────────────────────────────
  {
    id: 'his-001',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'leve',
    text: 'Qual foi a primeira coisa que você reparou em mim?',
    followUps: ['Você lembra o que passou pela sua cabeça naquele instante?'],
  },
  {
    id: 'his-002',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'conectar',
    text: 'Em que momento você percebeu que isso aqui era sério?',
    followUps: ['O que você fez com essa percepção na época?'],
  },
  {
    id: 'his-003',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'leve',
    text: 'Qual história nossa você mais gosta de contar para os outros?',
    followUps: ['Qual parte você sempre exagera um pouco?'],
  },
  {
    id: 'his-004',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'conectar',
    text: 'Qual dia comum, sem nada de especial, ficou guardado na sua memória?',
    followUps: ['O que aquele dia tinha que os outros não tinham?'],
  },
  {
    id: 'his-005',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'leve',
    text: 'Qual foi o programa mais improvisado nosso que deu muito certo?',
    followUps: ['O que fez aquilo funcionar tão bem?'],
  },
  {
    id: 'his-006',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'conectar',
    text: 'Qual viagem ou passeio nosso você mais gostou?',
    followUps: ['O que daquele dia você queria repetir nos próximos que a gente fizer?'],
  },
  {
    id: 'his-007',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'leve',
    text: 'Qual mico a gente pagou junto que hoje só dá risada?',
    followUps: ['Qual foi a cara que eu fiz na hora?'],
  },
  {
    id: 'his-008',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'profundo',
    text: 'Qual momento nosso te fez sentir que podia confiar em mim de verdade?',
    followUps: ['O que eu fiz ali que importou tanto?'],
  },
  {
    id: 'his-009',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'leve',
    text: 'Como você contou para alguém, pela primeira vez, que estava comigo?',
    followUps: ['Qual foi a reação da pessoa?'],
  },
  {
    id: 'his-010',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'conectar',
    text: 'Tem algum lugar que virou nosso sem a gente combinar?',
    followUps: ['O que aconteceu lá para ele virar isso?'],
  },
  {
    id: 'his-011',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'leve',
    text: 'Qual foi a melhor risada que a gente deu junto?',
    followUps: ['O que exatamente foi tão engraçado?'],
  },
  {
    id: 'his-012',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'conectar',
    text: 'Qual coisa nova você só experimentou por minha causa?',
    followUps: ['O que ficou com você daquela experiência?'],
  },
  {
    id: 'his-013',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'profundo',
    text: 'Qual fase corrida a gente atravessou junto e saiu melhor?',
    followUps: ['O que a gente aprendeu a fazer naquela época?'],
  },
  {
    id: 'his-014',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'leve',
    text: 'Qual foi o presente mais certeiro que você já me deu?',
    followUps: ['Como você teve essa ideia?'],
  },
  {
    id: 'his-015',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'conectar',
    text: 'Qual conversa nossa você lembra até hoje?',
    followUps: ['O que ela mudou para você?'],
  },
  {
    id: 'his-016',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'leve',
    text: 'Qual foi o nosso encontro mais estranho e engraçado?',
    followUps: ['O que deu errado exatamente?'],
  },
  {
    id: 'his-017',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'conectar',
    text: 'Quando você percebeu que já sentia saudade de mim?',
    followUps: ['Como era essa saudade?'],
  },
  {
    id: 'his-018',
    kind: 'pergunta',
    category: 'Nossa história',
    depth: 'profundo',
    text: 'Olhando para trás, qual escolha nossa você faria de novo sem pensar?',
    followUps: ['O que aquela escolha trouxe para a gente?'],
  },

  // ─── Sobre você ──────────────────────────────────────────────────────────
  {
    id: 'voc-001',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'leve',
    text: 'Qual parte do seu dia é só sua, e você não abre mão?',
    followUps: ['O que ela te dá?'],
  },
  {
    id: 'voc-002',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'conectar',
    text: 'Do que você tem orgulho em você e quase nunca comenta?',
    followUps: ['O que te faz não falar disso?'],
  },
  {
    id: 'voc-003',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'profundo',
    text: 'O que te faz olhar para um dia e sentir que ele valeu a pena?',
    followUps: ['Quando foi a última vez que você teve um dia desses?'],
  },
  {
    id: 'voc-004',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'leve',
    text: 'Qual coisa boba te deixa de bom humor na hora?',
    followUps: ['Desde quando é assim?'],
  },
  {
    id: 'voc-005',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'conectar',
    text: 'O que você faz quando precisa se recompor?',
    followUps: ['Como eu posso ajudar sem atrapalhar?'],
  },
  {
    id: 'voc-006',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'leve',
    text: 'Se você tivesse uma tarde livre, sem cobrança nenhuma, o que faria?',
    followUps: ['O que te impede de fazer isso mais vezes?'],
  },
  {
    id: 'voc-007',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'profundo',
    text: 'Qual habilidade sua você gostaria de usar mais?',
    followUps: ['Onde ela caberia na sua vida hoje?'],
  },
  {
    id: 'voc-008',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'conectar',
    text: 'O que você aprendeu sobre si mesmo nos últimos anos?',
    followUps: ['O que mudou na prática?'],
  },
  {
    id: 'voc-009',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'leve',
    text: 'Qual foi a melhor coisa que você comprou por impulso?',
    followUps: ['O que te convenceu na hora?'],
  },
  {
    id: 'voc-010',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'conectar',
    text: 'Que tipo de elogio te marca de verdade?',
    followUps: ['Quem já te disse algo assim?'],
  },
  {
    id: 'voc-011',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'profundo',
    text: 'O que você quer estar fazendo com o seu tempo daqui a alguns anos?',
    followUps: ['O que já existe hoje que caminha para lá?'],
  },
  {
    id: 'voc-012',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'leve',
    text: 'Qual assunto você explicaria por uma hora sem cansar?',
    followUps: ['Como você se interessou por isso?'],
  },
  {
    id: 'voc-013',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'conectar',
    text: 'Que assunto novo puxou a sua atenção ultimamente?',
    followUps: ['O que você já foi atrás sobre isso?'],
  },
  {
    id: 'voc-014',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'profundo',
    text: 'Que pessoa te ensinou algo que você carrega até hoje?',
    followUps: ['O que exatamente você aprendeu com ela?'],
  },
  {
    id: 'voc-015',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'leve',
    text: 'Qual fase da sua vida foi a mais divertida até agora?',
    followUps: ['O que você trouxe daquela fase para hoje?'],
  },
  {
    id: 'voc-016',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'conectar',
    text: 'Em que situações você sente que está sendo mais você?',
    followUps: ['O que precisa estar acontecendo para isso?'],
  },
  {
    id: 'voc-017',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'leve',
    text: 'Qual talento inútil você tem?',
    followUps: ['Como você descobriu isso?'],
  },
  {
    id: 'voc-018',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'conectar',
    text: 'O que te dá energia num dia normal?',
    followUps: ['Quanto disso você teve esta semana?'],
  },
  {
    id: 'voc-019',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'profundo',
    text: 'Qual sonho seu ainda está vivo, mesmo sem data para acontecer?',
    followUps: ['Qual seria o primeiro passo pequeno dele?'],
  },
  {
    id: 'voc-020',
    kind: 'pergunta',
    category: 'Sobre você',
    depth: 'leve',
    text: 'Se você pudesse passar um dia na pele de alguém, quem seria?',
    followUps: ['O que você mais ia querer entender?'],
  },

  // ─── Amor e carinho ──────────────────────────────────────────────────────
  {
    id: 'amo-001',
    kind: 'pergunta',
    category: 'Amor e carinho',
    depth: 'conectar',
    text: 'O que eu faço que te faz sentir cuidado sem eu dizer nada?',
    followUps: ['Como você percebe isso na hora?'],
  },
  {
    id: 'amo-002',
    kind: 'pergunta',
    category: 'Amor e carinho',
    depth: 'leve',
    text: 'Você prefere carinho em público ou só entre nós dois?',
    followUps: ['Sempre foi assim para você?'],
  },
  {
    id: 'amo-003',
    kind: 'pergunta',
    category: 'Amor e carinho',
    depth: 'profundo',
    text: 'Como você aprendeu a demonstrar afeto?',
    followUps: ['O que disso combina com você hoje?'],
  },
  {
    id: 'amo-004',
    kind: 'pergunta',
    category: 'Amor e carinho',
    depth: 'conectar',
    text: 'Qual gesto pequeno meu vale mais do que um presente?',
    followUps: ['Quando foi a última vez que eu fiz isso?'],
  },
  {
    id: 'amo-005',
    kind: 'pergunta',
    category: 'Amor e carinho',
    depth: 'leve',
    text: 'Qual é a melhor forma de te acordar num domingo?',
    followUps: ['E a pior?'],
  },
  {
    id: 'amo-006',
    kind: 'pergunta',
    category: 'Amor e carinho',
    depth: 'conectar',
    text: 'Como você gosta de ser recebido quando a gente se encontra depois de um dia longo?',
    followUps: ['O que eu já costumo fazer que funciona?'],
  },
  {
    id: 'amo-007',
    kind: 'pergunta',
    category: 'Amor e carinho',
    depth: 'profundo',
    text: 'O que te faz sentir escolhido por mim?',
    followUps: ['Qual foi a última vez que você sentiu isso?'],
  },
  {
    id: 'amo-008',
    kind: 'pergunta',
    category: 'Amor e carinho',
    depth: 'leve',
    text: 'Bilhete, áudio ou mensagem no meio do dia: o que te ganha mais?',
    followUps: ['O que você gosta de receber nele?'],
  },
  {
    id: 'amo-009',
    kind: 'pergunta',
    category: 'Amor e carinho',
    depth: 'conectar',
    text: 'Em que tipo de dia você mais precisa de um abraço?',
    followUps: ['Como eu percebo que é um desses dias?'],
  },
  {
    id: 'amo-010',
    kind: 'pergunta',
    category: 'Amor e carinho',
    depth: 'conectar',
    text: 'Qual carinho você gosta de receber e quase nunca pede?',
    followUps: ['O que te faz não pedir?'],
  },
  {
    id: 'amo-011',
    kind: 'pergunta',
    category: 'Amor e carinho',
    depth: 'profundo',
    text: 'O que significa ser amado no dia a dia, longe das datas especiais?',
    followUps: ['Como isso aparece entre a gente hoje?'],
  },
  {
    id: 'amo-012',
    kind: 'pergunta',
    category: 'Amor e carinho',
    depth: 'leve',
    text: 'Qual música te faz pensar em mim?',
    followUps: ['Qual parte dela é a nossa cara?'],
  },
  {
    id: 'amo-013',
    kind: 'pergunta',
    category: 'Amor e carinho',
    depth: 'conectar',
    text: 'Como você gosta que eu cuide de você num dia em que você chega sem energia?',
    followUps: ['O que você mais quer nessas horas: silêncio ou companhia?'],
  },
  {
    id: 'amo-014',
    kind: 'acao',
    category: 'Amor e carinho',
    depth: 'conectar',
    text: 'Olhe nos olhos da outra pessoa por dez segundos, sem falar nada.',
  },
  {
    id: 'amo-015',
    kind: 'acao',
    category: 'Amor e carinho',
    depth: 'leve',
    text: 'Faça um elogio sobre algo que a outra pessoa fez esta semana.',
  },
  {
    id: 'amo-016',
    kind: 'acao',
    category: 'Amor e carinho',
    depth: 'profundo',
    text: 'Conte um momento em que você se sentiu muito cuidado por mim.',
  },
  {
    id: 'amo-017',
    kind: 'acao',
    category: 'Amor e carinho',
    depth: 'conectar',
    text: 'Dê um abraço longo, daqueles que só terminam quando os dois soltam.',
  },
  {
    id: 'amo-018',
    kind: 'acao',
    category: 'Amor e carinho',
    depth: 'leve',
    text: 'Mande agora uma mensagem carinhosa para a outra pessoa, mesmo estando do lado.',
  },

  // ─── Comunicação ─────────────────────────────────────────────────────────
  {
    id: 'com-001',
    kind: 'pergunta',
    category: 'Comunicação',
    depth: 'conectar',
    text: 'Como você prefere que eu te avise que quero conversar sobre algo sério?',
    followUps: ['Qual hora do dia funciona melhor para você?'],
  },
  {
    id: 'com-002',
    kind: 'pergunta',
    category: 'Comunicação',
    depth: 'profundo',
    text: 'Quando a gente discorda, o que te ajuda a continuar ouvindo?',
    followUps: ['O que eu posso fazer para facilitar isso?'],
  },
  {
    id: 'com-003',
    kind: 'pergunta',
    category: 'Comunicação',
    depth: 'conectar',
    text: 'Como eu percebo que você está precisando de espaço?',
    followUps: ['Você prefere avisar ou que eu pergunte?'],
  },
  {
    id: 'com-004',
    kind: 'pergunta',
    category: 'Comunicação',
    depth: 'leve',
    text: 'Quem de nós dois fala mais rápido quando se empolga?',
    followUps: ['Como o outro reage a isso?'],
  },
  {
    id: 'com-005',
    kind: 'pergunta',
    category: 'Comunicação',
    depth: 'profundo',
    text: 'O que te ajuda a voltar a conversar depois de um desentendimento?',
    followUps: ['Como você gosta que a gente feche o assunto?'],
  },
  {
    id: 'com-006',
    kind: 'pergunta',
    category: 'Comunicação',
    depth: 'conectar',
    text: 'Você prefere pensar antes de falar ou ir pensando enquanto fala?',
    followUps: ['Como o seu jeito e o meu se encaixam?'],
  },
  {
    id: 'com-007',
    kind: 'pergunta',
    category: 'Comunicação',
    depth: 'conectar',
    text: 'Qual assunto a gente conversa melhor do que a maioria dos casais?',
    followUps: ['Por que esse assunto flui tanto entre nós?'],
  },
  {
    id: 'com-008',
    kind: 'pergunta',
    category: 'Comunicação',
    depth: 'profundo',
    text: 'O que eu digo que te acalma quando você está a mil?',
    followUps: ['Tem alguma frase que sempre funciona?'],
  },
  {
    id: 'com-009',
    kind: 'pergunta',
    category: 'Comunicação',
    depth: 'conectar',
    text: 'Você prefere resolver na hora ou dormir e falar no dia seguinte?',
    followUps: ['Como a gente faz quando cada um quer uma coisa?'],
  },
  {
    id: 'com-010',
    kind: 'pergunta',
    category: 'Comunicação',
    depth: 'leve',
    text: 'Qual olhar nosso já diz tudo sem palavra nenhuma?',
    followUps: ['Quando foi a última vez que ele apareceu?'],
  },
  {
    id: 'com-011',
    kind: 'pergunta',
    category: 'Comunicação',
    depth: 'profundo',
    text: 'O que você gostaria que eu perguntasse mais vezes?',
    followUps: ['O que faz você não trazer esse assunto sozinho?'],
  },
  {
    id: 'com-012',
    kind: 'pergunta',
    category: 'Comunicação',
    depth: 'conectar',
    text: 'Como você gosta de receber uma notícia boa minha?',
    followUps: ['E uma chatice do dia a dia?'],
  },
  {
    id: 'com-013',
    kind: 'pergunta',
    category: 'Comunicação',
    depth: 'leve',
    text: 'A gente conversa mais por mensagem ou ao vivo?',
    followUps: ['Em qual dos dois a gente se entende melhor?'],
  },
  {
    id: 'com-014',
    kind: 'pergunta',
    category: 'Comunicação',
    depth: 'profundo',
    text: 'O que você gostaria que a gente conversasse com mais calma?',
    followUps: ['Qual seria um bom momento para essa conversa?'],
  },

  // ─── Futuro ──────────────────────────────────────────────────────────────
  {
    id: 'fut-001',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'conectar',
    text: 'Qual lugar você quer conhecer comigo?',
    followUps: ['O que a gente faria no primeiro dia lá?'],
  },
  {
    id: 'fut-002',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'profundo',
    text: 'Como você quer que seja um domingo nosso daqui a cinco anos?',
    followUps: ['O que já dá para começar a fazer hoje?'],
  },
  {
    id: 'fut-003',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'conectar',
    text: 'Que tradição nova você gostaria que a gente criasse?',
    followUps: ['Quando a gente poderia começar?'],
  },
  {
    id: 'fut-004',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'profundo',
    text: 'O que você quer que continue igual entre a gente daqui a muito tempo?',
    followUps: ['Como a gente protege isso?'],
  },
  {
    id: 'fut-005',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'leve',
    text: 'Qual coisa aleatória você quer muito experimentar comigo?',
    followUps: ['O que te atrai nisso?'],
  },
  {
    id: 'fut-006',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'conectar',
    text: 'Qual projeto seu você quer que eu acompanhe de perto?',
    followUps: ['Como eu posso ajudar sem te sufocar?'],
  },
  {
    id: 'fut-007',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'profundo',
    text: 'O que é uma vida boa para você?',
    followUps: ['Quanto da sua vida hoje já é assim?'],
  },
  {
    id: 'fut-008',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'conectar',
    text: 'Se a gente tivesse um ano inteiro livre junto, o que faria?',
    followUps: ['Qual parte desse plano cabe numa semana de folga?'],
  },
  {
    id: 'fut-009',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'conectar',
    text: 'Qual habilidade você quer aprender comigo?',
    followUps: ['Por onde a gente começaria?'],
  },
  {
    id: 'fut-010',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'profundo',
    text: 'Que tipo de casal você quer que a gente seja daqui a dez anos?',
    followUps: ['O que a gente já faz que caminha para isso?'],
  },
  {
    id: 'fut-011',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'leve',
    text: 'Se a gente pudesse morar em qualquer lugar por um mês, onde seria?',
    followUps: ['Como seria a nossa rotina lá?'],
  },
  {
    id: 'fut-012',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'conectar',
    text: 'Qual é a próxima coisa que você quer comemorar comigo?',
    followUps: ['Como você gostaria que fosse essa comemoração?'],
  },
  {
    id: 'fut-013',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'profundo',
    text: 'O que você espera de mim quando o ano ficar mais pesado?',
    followUps: ['Como você gosta de ser apoiado nessas horas?'],
  },
  {
    id: 'fut-014',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'conectar',
    text: 'Qual sonho seu eu posso ajudar a empurrar este ano?',
    followUps: ['Qual seria o primeiro passo?'],
  },
  {
    id: 'fut-015',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'leve',
    text: 'Como seria a nossa casa dos sonhos em uma frase?',
    followUps: ['Qual cômodo você descreveria primeiro?'],
  },
  {
    id: 'fut-016',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'profundo',
    text: 'O que você quer poder dizer sobre a gente daqui a vinte anos?',
    followUps: ['O que a gente precisa cuidar para isso ser verdade?'],
  },
  {
    id: 'fut-017',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'conectar',
    text: 'Tem alguma coisa que você quer fazer comigo antes do fim do ano?',
    followUps: ['O que falta para acontecer?'],
  },
  {
    id: 'fut-018',
    kind: 'pergunta',
    category: 'Futuro',
    depth: 'leve',
    text: 'Se a gente ganhasse uma viagem surpresa amanhã, o que você levaria na mala?',
    followUps: ['O que você contaria comigo para levar?'],
  },

  // ─── Vida juntos ─────────────────────────────────────────────────────────
  {
    id: 'vid-001',
    kind: 'pergunta',
    category: 'Vida juntos',
    depth: 'leve',
    text: 'Qual parte da nossa rotina você mais gosta?',
    followUps: ['O que ela tem de bom?'],
  },
  {
    id: 'vid-002',
    kind: 'pergunta',
    category: 'Vida juntos',
    depth: 'conectar',
    text: 'Qual tarefa do dia a dia você prefere fazer e qual prefere passar para mim?',
    followUps: ['Como a gente pode ajustar isso?'],
  },
  {
    id: 'vid-003',
    kind: 'pergunta',
    category: 'Vida juntos',
    depth: 'leve',
    text: 'Como seria o nosso fim de semana perfeito sem sair de casa?',
    followUps: ['O que a gente comeria?'],
  },
  {
    id: 'vid-004',
    kind: 'pergunta',
    category: 'Vida juntos',
    depth: 'conectar',
    text: 'O que faz um dia comum virar um dia bom para você?',
    followUps: ['Quantos dias assim a gente teve este mês?'],
  },
  {
    id: 'vid-005',
    kind: 'pergunta',
    category: 'Vida juntos',
    depth: 'profundo',
    text: 'O que você mais quer que a gente cuide melhor na nossa rotina?',
    followUps: ['Qual mudança pequena já ajudaria?'],
  },
  {
    id: 'vid-006',
    kind: 'pergunta',
    category: 'Vida juntos',
    depth: 'leve',
    text: 'Quem faz mais bagunça de nós dois, sem mentir?',
    followUps: ['Onde isso aparece mais?'],
  },
  {
    id: 'vid-007',
    kind: 'pergunta',
    category: 'Vida juntos',
    depth: 'conectar',
    text: 'Como você gosta que a gente divida o tempo entre ficar junto e o tempo que é só seu?',
    followUps: ['Essa conta está boa para você agora?'],
  },
  {
    id: 'vid-008',
    kind: 'pergunta',
    category: 'Vida juntos',
    depth: 'leve',
    text: 'Qual série ou filme a gente devia começar junto hoje?',
    followUps: ['Por que logo esse?'],
  },
  {
    id: 'vid-009',
    kind: 'pergunta',
    category: 'Vida juntos',
    depth: 'conectar',
    text: 'Qual pequeno ritual nosso você sentiria falta se acabasse?',
    followUps: ['Como ele começou?'],
  },
  {
    id: 'vid-010',
    kind: 'pergunta',
    category: 'Vida juntos',
    depth: 'profundo',
    text: 'O que a gente podia fazer para os dias corridos pesarem menos?',
    followUps: ['O que você tentaria primeiro?'],
  },
  {
    id: 'vid-011',
    kind: 'pergunta',
    category: 'Vida juntos',
    depth: 'leve',
    text: 'Se a gente tivesse um dia de folga juntos amanhã, qual seria o plano?',
    followUps: ['Quem escolheria a primeira parada?'],
  },
  {
    id: 'vid-012',
    kind: 'pergunta',
    category: 'Vida juntos',
    depth: 'conectar',
    text: 'Em que momento do dia você mais gosta de falar comigo?',
    followUps: ['O que a gente costuma conversar nessa hora?'],
  },
  {
    id: 'vid-013',
    kind: 'pergunta',
    category: 'Vida juntos',
    depth: 'profundo',
    text: 'O que deixa o lugar onde a gente fica junto com cara de nosso?',
    followUps: ['O que você acrescentaria nele?'],
  },
  {
    id: 'vid-014',
    kind: 'pergunta',
    category: 'Vida juntos',
    depth: 'leve',
    text: 'Qual comida define a gente?',
    followUps: ['Que história tem por trás dela?'],
  },

  // ─── Leve e divertido ────────────────────────────────────────────────────
  {
    id: 'lev-001',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Qual apelido ridículo você me daria se pudesse escolher um agora?',
    followUps: ['Por que logo esse?'],
  },
  {
    id: 'lev-002',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Se a gente entrasse numa competição de casal, em qual prova ganharia?',
    followUps: ['E em qual a gente passaria vergonha?'],
  },
  {
    id: 'lev-003',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Qual comida você jamais dividiria, nem comigo?',
    followUps: ['O que acontece se eu pedir um pedaço?'],
  },
  {
    id: 'lev-004',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Qual seria o seu superpoder inútil dos sonhos?',
    followUps: ['Como você usaria ele no dia a dia?'],
  },
  {
    id: 'lev-005',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Se a gente virasse uma dupla de comédia, quem seria o cérebro?',
    followUps: ['E quem estragaria o plano?'],
  },
  {
    id: 'lev-006',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Qual personagem de filme mais parece comigo?',
    followUps: ['E qual parece com você?'],
  },
  {
    id: 'lev-007',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Qual a coisa mais estranha que você já comeu?',
    followUps: ['Você comeria de novo?'],
  },
  {
    id: 'lev-008',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Se a gente tivesse uma banda, qual seria o nome?',
    followUps: ['Que tipo de música a gente tocaria?'],
  },
  {
    id: 'lev-009',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Qual moda antiga você usaria de novo sem vergonha nenhuma?',
    followUps: ['Você tem foto dessa época?'],
  },
  {
    id: 'lev-010',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Qual bicho você acha que eu teria sido em outra vida?',
    followUps: ['E você, qual seria?'],
  },
  {
    id: 'lev-011',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Qual é a sua teoria maluca favorita?',
    followUps: ['Quem mais acredita nisso com você?'],
  },
  {
    id: 'lev-012',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Se a gente pudesse ter um animal exótico em casa, qual seria?',
    followUps: ['Quem cuidaria dele de verdade?'],
  },
  {
    id: 'lev-013',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Qual programa de TV você fingiria não assistir?',
    followUps: ['Qual episódio você já viu mais de uma vez?'],
  },
  {
    id: 'lev-014',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Qual seria o nosso disfarce se a gente precisasse sumir por um dia?',
    followUps: ['Qual nome falso você usaria?'],
  },
  {
    id: 'lev-015',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Se você pudesse comer só uma coisa pelo resto do mês, qual seria?',
    followUps: ['Em quantos dias você desistiria?'],
  },
  {
    id: 'lev-016',
    kind: 'pergunta',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Qual emoji resume a nossa conversa no celular?',
    followUps: ['E qual resume você de manhã?'],
  },
  {
    id: 'lev-017',
    kind: 'acao',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Imite a outra pessoa acordando de manhã.',
  },
  {
    id: 'lev-018',
    kind: 'acao',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Conte uma lembrança de vocês dois que sempre te faz sorrir.',
  },
  {
    id: 'lev-019',
    kind: 'acao',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Invente um brinde para a gente e faça agora, em voz alta.',
  },
  {
    id: 'lev-020',
    kind: 'acao',
    category: 'Leve e divertido',
    depth: 'leve',
    text: 'Mostre a última foto engraçada que você salvou no celular.',
  },

  // ─── Valores ─────────────────────────────────────────────────────────────
  {
    id: 'val-001',
    kind: 'pergunta',
    category: 'Valores',
    depth: 'profundo',
    text: 'O que é inegociável para você na forma de tratar as pessoas?',
    followUps: ['De onde isso veio para você?'],
  },
  {
    id: 'val-002',
    kind: 'pergunta',
    category: 'Valores',
    depth: 'profundo',
    text: 'O que é ser generoso para você?',
    followUps: ['Quem te mostrou isso na prática?'],
  },
  {
    id: 'val-003',
    kind: 'pergunta',
    category: 'Valores',
    depth: 'profundo',
    text: 'Que tipo de lealdade importa para você numa relação?',
    followUps: ['Como ela aparece no dia a dia?'],
  },
  {
    id: 'val-004',
    kind: 'pergunta',
    category: 'Valores',
    depth: 'profundo',
    text: 'O que te faz respeitar alguém de verdade?',
    followUps: ['Quem na sua vida tem isso?'],
  },
  {
    id: 'val-005',
    kind: 'pergunta',
    category: 'Valores',
    depth: 'profundo',
    text: 'O que você quer que as pessoas sintam quando estão com você?',
    followUps: ['Onde você já consegue isso hoje?'],
  },
  {
    id: 'val-006',
    kind: 'pergunta',
    category: 'Valores',
    depth: 'profundo',
    text: 'Qual princípio você segue mesmo quando ele dá trabalho?',
    followUps: ['Quando foi a última vez que ele deu trabalho?'],
  },
  {
    id: 'val-007',
    kind: 'pergunta',
    category: 'Valores',
    depth: 'profundo',
    text: 'O que significa ser justo para você?',
    followUps: ['Onde isso é mais difícil de sustentar?'],
  },
  {
    id: 'val-008',
    kind: 'pergunta',
    category: 'Valores',
    depth: 'profundo',
    text: 'Que tipo de coragem você admira mais?',
    followUps: ['Onde você gostaria de ter mais dela?'],
  },
  {
    id: 'val-009',
    kind: 'pergunta',
    category: 'Valores',
    depth: 'profundo',
    text: 'O que é honestidade para você dentro de um casal?',
    followUps: ['Como a gente cuida disso entre nós?'],
  },
  {
    id: 'val-010',
    kind: 'pergunta',
    category: 'Valores',
    depth: 'profundo',
    text: 'Qual valor você gostaria que a gente carregasse junto?',
    followUps: ['Como ele apareceria nas nossas escolhas?'],
  },

  // ─── Intimidade (opt-in) ─────────────────────────────────────────────────
  {
    id: 'int-001',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'O que te deixa com vontade de ficar mais perto de mim?',
    followUps: ['Como eu percebo isso em você?'],
  },
  {
    id: 'int-002',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'Qual toque simples te desarma na hora?',
    followUps: ['Onde você mais gosta de receber esse toque?'],
  },
  {
    id: 'int-003',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'Qual roupa minha você mais gosta de ver em mim?',
    followUps: ['O que nela te chama atenção?'],
  },
  {
    id: 'int-004',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'O que te faz sentir desejado por mim?',
    followUps: ['Qual foi a última vez que você sentiu isso?'],
  },
  {
    id: 'int-005',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'Que clima deixa a noite melhor para você?',
    followUps: ['O que a gente poderia preparar para criar esse clima?'],
  },
  {
    id: 'int-006',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'Qual detalhe seu você gosta que eu note?',
    followUps: ['Como você prefere ouvir isso de mim?'],
  },
  {
    id: 'int-007',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'O que você acha mais atraente em mim que não tem nada a ver com aparência?',
    followUps: ['Quando isso aparece mais?'],
  },
  {
    id: 'int-008',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'Você gosta mais de ser surpreendido ou de saber o que vem?',
    followUps: ['O que torna a surpresa boa para você?'],
  },
  {
    id: 'int-009',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'O que te aproxima de mim no fim de um dia comum?',
    followUps: ['Como eu posso ajudar nisso?'],
  },
  {
    id: 'int-010',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'Qual carinho sem pressa é o seu preferido?',
    followUps: ['Em que momento do dia ele é melhor?'],
  },
  {
    id: 'int-011',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'O que você gostaria de me ouvir dizer mais vezes quando a gente está a sós?',
    followUps: ['O que essas palavras te fazem sentir?'],
  },
  {
    id: 'int-012',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'Qual lembrança nossa ainda te dá um arrepio?',
    followUps: ['O que daquele momento ficou tão marcado?'],
  },
  {
    id: 'int-013',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'Você prefere começar a noite devagar ou já com o clima ligado?',
    followUps: ['O que te ajuda a entrar no clima?'],
  },
  {
    id: 'int-014',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'O que eu faço que te faz se sentir atraente?',
    followUps: ['Como eu posso fazer isso mais vezes?'],
  },
  {
    id: 'int-015',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'Qual beijo nosso você repetiria agora?',
    followUps: ['O que aquele beijo tinha de diferente?'],
  },
  {
    id: 'int-016',
    kind: 'pergunta',
    category: 'Intimidade',
    depth: 'intimidade',
    text: 'Que tipo de proximidade te faz bem mesmo sem levar a mais nada?',
    followUps: ['Quando a gente tem mais disso?'],
  },
];
