import type { LikelyQuestion } from "./likely-types";

/**
 * Banco de perguntas do "Quem é Mais Provável?".
 *
 * O app SEMPRE renderiza o prefixo "Quem é mais provável de..." antes do `text`.
 * Por isso cada `text` é apenas a continuação da frase: começa em minúscula,
 * termina com "?" e nunca repete o prefixo.
 *
 * Critérios:
 * - 8 categorias x 25 perguntas = 200, ids sequenciais por prefixo de categoria.
 * - Intensidade: ~12 `leve`, ~9 `moderado`, ~4 `pesado` por categoria.
 *   Exceções: `Família` é 100% `leve` (roda com crianças na mesa) e
 *   `Trabalho` vai no máximo até `moderado` (são colegas, não amigos íntimos).
 * - Segurança: nada de saúde física ou mental, traumas, aparência, raça,
 *   religião, orientação sexual, identidade de gênero, dinheiro real, crimes,
 *   violência, morte, doença, sexo explícito ou drogas. Até o `pesado` precisa
 *   ser algo de que a pessoa apontada consiga rir junto.
 * - Álcool aparece só em `Festa`, de forma leve e não depreciativa.
 */
export const QUESTIONS: LikelyQuestion[] = [
  // Engraçado — leve e absurdo
  {
    id: "eng-001",
    category: "Engraçado",
    intensity: "leve",
    text: "cair tentando fazer uma dancinha?",
  },
  {
    id: "eng-002",
    category: "Engraçado",
    intensity: "leve",
    text: "perder o celular dentro de casa?",
  },
  {
    id: "eng-003",
    category: "Engraçado",
    intensity: "leve",
    text: "falar com o pet como se ele fosse responder?",
  },
  {
    id: "eng-004",
    category: "Engraçado",
    intensity: "leve",
    text: "rir sozinho lembrando de uma bobagem?",
  },
  {
    id: "eng-005",
    category: "Engraçado",
    intensity: "leve",
    text: "acenar de volta para alguém que estava acenando para outra pessoa?",
  },
  {
    id: "eng-006",
    category: "Engraçado",
    intensity: "leve",
    text: "esquecer o próprio aniversário?",
  },
  {
    id: "eng-007",
    category: "Engraçado",
    intensity: "leve",
    text: "empurrar a porta que era pra puxar?",
  },
  {
    id: "eng-008",
    category: "Engraçado",
    intensity: "leve",
    text: "cantar a letra errada de uma música por anos?",
  },
  {
    id: "eng-009",
    category: "Engraçado",
    intensity: "leve",
    text: "dormir com a boca aberta no ônibus?",
  },
  {
    id: "eng-010",
    category: "Engraçado",
    intensity: "leve",
    text: "conversar com a comida dentro do micro-ondas?",
  },
  {
    id: "eng-011",
    category: "Engraçado",
    intensity: "leve",
    text: "usar a camiseta do avesso um dia inteiro sem notar?",
  },
  {
    id: "eng-012",
    category: "Engraçado",
    intensity: "leve",
    text: "levar um susto com o próprio reflexo?",
  },
  {
    id: "eng-013",
    category: "Engraçado",
    intensity: "moderado",
    text: 'chamar a professora de "mãe" sem pensar?',
  },
  {
    id: "eng-014",
    category: "Engraçado",
    intensity: "moderado",
    text: 'mandar áudio de 8 minutos para responder "ok"?',
  },
  {
    id: "eng-015",
    category: "Engraçado",
    intensity: "moderado",
    text: "rir na hora mais errada possível?",
  },
  {
    id: "eng-016",
    category: "Engraçado",
    intensity: "moderado",
    text: "dançar na cozinha achando que ninguém estava vendo?",
  },
  {
    id: "eng-017",
    category: "Engraçado",
    intensity: "moderado",
    text: "imitar o jeito de falar de alguém na frente da pessoa?",
  },
  {
    id: "eng-018",
    category: "Engraçado",
    intensity: "moderado",
    text: "confundir os nomes de dois amigos na mesma frase?",
  },
  {
    id: "eng-019",
    category: "Engraçado",
    intensity: "moderado",
    text: "gritar de susto num filme antes do susto acontecer?",
  },
  {
    id: "eng-020",
    category: "Engraçado",
    intensity: "moderado",
    text: "escorregar no piso molhado e levantar fingindo que foi de propósito?",
  },
  {
    id: "eng-021",
    category: "Engraçado",
    intensity: "moderado",
    text: "começar a falar e esquecer no meio o que ia dizer?",
  },
  {
    id: "eng-022",
    category: "Engraçado",
    intensity: "pesado",
    text: "mandar no grupo uma mensagem que era pra conversa privada?",
  },
  {
    id: "eng-023",
    category: "Engraçado",
    intensity: "pesado",
    text: "esquecer que estava no viva-voz e continuar falando?",
  },
  {
    id: "eng-024",
    category: "Engraçado",
    intensity: "pesado",
    text: "ter um print antigo seu guardado por alguém do grupo?",
  },
  {
    id: "eng-025",
    category: "Engraçado",
    intensity: "pesado",
    text: "se entregar sozinho tentando disfarçar uma mentirinha?",
  },

  // Exposed — pequenas revelações sobre hábitos
  {
    id: "exp-001",
    category: "Exposed",
    intensity: "leve",
    text: "reler a própria mensagem só pra ver se ficou boa?",
  },
  {
    id: "exp-002",
    category: "Exposed",
    intensity: "leve",
    text: "fingir que assistiu a série que todo mundo comenta?",
  },
  {
    id: "exp-003",
    category: "Exposed",
    intensity: "leve",
    text: "deixar a louça de molho até o dia seguinte?",
  },
  {
    id: "exp-004",
    category: "Exposed",
    intensity: "leve",
    text: "ter mais de cem abas abertas no celular?",
  },
  {
    id: "exp-005",
    category: "Exposed",
    intensity: "leve",
    text: "comer de pé na frente da geladeira aberta?",
  },
  {
    id: "exp-006",
    category: "Exposed",
    intensity: "leve",
    text: "guardar sacolinha dentro de outra sacolinha?",
  },
  {
    id: "exp-007",
    category: "Exposed",
    intensity: "leve",
    text: "ter um alarme diário e não lembrar pra que serve?",
  },
  {
    id: "exp-008",
    category: "Exposed",
    intensity: "leve",
    text: "ensaiar o que vai falar antes de ligar pra alguém?",
  },
  {
    id: "exp-009",
    category: "Exposed",
    intensity: "leve",
    text: "usar quase a mesma senha em tudo?",
  },
  {
    id: "exp-010",
    category: "Exposed",
    intensity: "leve",
    text: "deixar tudo pro último dia possível?",
  },
  {
    id: "exp-011",
    category: "Exposed",
    intensity: "leve",
    text: "ter uma playlist que ninguém pode ver?",
  },
  {
    id: "exp-012",
    category: "Exposed",
    intensity: "leve",
    text: "ler a mensagem e responder três dias depois?",
  },
  {
    id: "exp-013",
    category: "Exposed",
    intensity: "moderado",
    text: 'falar "já tô saindo" ainda de toalha?',
  },
  {
    id: "exp-014",
    category: "Exposed",
    intensity: "moderado",
    text: "stalkear um perfil até chegar em 2016?",
  },
  {
    id: "exp-015",
    category: "Exposed",
    intensity: "moderado",
    text: "treinar no chuveiro a resposta afiada de uma discussão que já passou?",
  },
  {
    id: "exp-016",
    category: "Exposed",
    intensity: "moderado",
    text: "anotar na lista uma tarefa que já fez só pra ter o que riscar?",
  },
  {
    id: "exp-017",
    category: "Exposed",
    intensity: "moderado",
    text: "ver os stories de todo mundo e nunca postar nada?",
  },
  {
    id: "exp-018",
    category: "Exposed",
    intensity: "moderado",
    text: "fingir que a ligação caiu pra encerrar a conversa?",
  },
  {
    id: "exp-019",
    category: "Exposed",
    intensity: "moderado",
    text: 'mandar o mesmo "bom dia" copiado pra dez pessoas?',
  },
  {
    id: "exp-020",
    category: "Exposed",
    intensity: "moderado",
    text: "comer escondido pra não ter que dividir?",
  },
  {
    id: "exp-021",
    category: "Exposed",
    intensity: "moderado",
    text: "dizer que está no trânsito ainda dentro de casa?",
  },
  {
    id: "exp-022",
    category: "Exposed",
    intensity: "pesado",
    text: "ter mensagens escritas que nunca teve coragem de enviar?",
  },
  {
    id: "exp-023",
    category: "Exposed",
    intensity: "pesado",
    text: "reler conversas antigas de madrugada?",
  },
  {
    id: "exp-024",
    category: "Exposed",
    intensity: "pesado",
    text: "manter um perfil secreto só pra observar?",
  },
  {
    id: "exp-025",
    category: "Exposed",
    intensity: "pesado",
    text: "ter contado uma mentirinha que virou história oficial do grupo?",
  },

  // Caos — provocativo, treta leve
  {
    id: "cao-001",
    category: "Caos",
    intensity: "leve",
    text: "começar uma discussão sobre o melhor sabor de pizza?",
  },
  {
    id: "cao-002",
    category: "Caos",
    intensity: "leve",
    text: "mudar o combinado do rolê em cima da hora?",
  },
  {
    id: "cao-003",
    category: "Caos",
    intensity: "leve",
    text: 'responder "kkkk" numa conversa séria?',
  },
  {
    id: "cao-004",
    category: "Caos",
    intensity: "leve",
    text: "comer o último pedaço sem perguntar de quem era?",
  },
  {
    id: "cao-005",
    category: "Caos",
    intensity: "leve",
    text: "colocar música alta às sete da manhã?",
  },
  {
    id: "cao-006",
    category: "Caos",
    intensity: "leve",
    text: "apagar a mensagem depois de todos terem lido?",
  },
  {
    id: "cao-007",
    category: "Caos",
    intensity: "leve",
    text: "mexer no controle do ar sem consultar ninguém?",
  },
  {
    id: "cao-008",
    category: "Caos",
    intensity: "leve",
    text: "contar o final do filme sem avisar?",
  },
  {
    id: "cao-009",
    category: "Caos",
    intensity: "leve",
    text: "trocar a playlist no meio da música?",
  },
  {
    id: "cao-010",
    category: "Caos",
    intensity: "leve",
    text: "responder só com figurinha enquanto o grupo tenta decidir algo?",
  },
  {
    id: "cao-011",
    category: "Caos",
    intensity: "leve",
    text: "chamar todos pra um jogo e mudar a regra no meio?",
  },
  {
    id: "cao-012",
    category: "Caos",
    intensity: "leve",
    text: "acordar a casa toda procurando o carregador?",
  },
  {
    id: "cao-013",
    category: "Caos",
    intensity: "moderado",
    text: "começar uma treta no grupo e sumir depois?",
  },
  {
    id: "cao-014",
    category: "Caos",
    intensity: "moderado",
    text: 'mandar "precisamos conversar" e demorar duas horas pra explicar?',
  },
  {
    id: "cao-015",
    category: "Caos",
    intensity: "moderado",
    text: "contar uma fofoca justo pra pessoa errada?",
  },
  {
    id: "cao-016",
    category: "Caos",
    intensity: "moderado",
    text: "aceitar os dois convites da mesma noite?",
  },
  {
    id: "cao-017",
    category: "Caos",
    intensity: "moderado",
    text: "puxar assunto polêmico justo na hora da foto?",
  },
  {
    id: "cao-018",
    category: "Caos",
    intensity: "moderado",
    text: "criar um grupo paralelo sem uma pessoa?",
  },
  {
    id: "cao-019",
    category: "Caos",
    intensity: "moderado",
    text: "fazer cara de quem discordou e não falar nada?",
  },
  {
    id: "cao-020",
    category: "Caos",
    intensity: "moderado",
    text: "deixar todos no vácuo justo na hora de fechar o programa?",
  },
  {
    id: "cao-021",
    category: "Caos",
    intensity: "moderado",
    text: "entrar numa discussão que não era sua só pra opinar?",
  },
  {
    id: "cao-022",
    category: "Caos",
    intensity: "pesado",
    text: "dar unfollow em alguém por causa de uma discussão?",
  },
  {
    id: "cao-023",
    category: "Caos",
    intensity: "pesado",
    text: "guardar mágoa de uma brincadeira de anos atrás?",
  },
  {
    id: "cao-024",
    category: "Caos",
    intensity: "pesado",
    text: "mandar print de conversa pra provar que estava certo?",
  },
  {
    id: "cao-025",
    category: "Caos",
    intensity: "pesado",
    text: "ficar de mal com alguém sem nunca explicar o motivo?",
  },

  // Relacionamentos — namoro, crush, ex
  {
    id: "rel-001",
    category: "Relacionamentos",
    intensity: "leve",
    text: "se apaixonar numa viagem de uma semana?",
  },
  {
    id: "rel-002",
    category: "Relacionamentos",
    intensity: "leve",
    text: "casar primeiro?",
  },
  {
    id: "rel-003",
    category: "Relacionamentos",
    intensity: "leve",
    text: "pedir o número e nunca chamar?",
  },
  {
    id: "rel-004",
    category: "Relacionamentos",
    intensity: "leve",
    text: "levar flores sem nenhum motivo?",
  },
  {
    id: "rel-005",
    category: "Relacionamentos",
    intensity: "leve",
    text: "escolher o filme do encontro e reclamar do filme?",
  },
  {
    id: "rel-006",
    category: "Relacionamentos",
    intensity: "leve",
    text: "planejar o pedido de namoro com apresentação de slides?",
  },
  {
    id: "rel-007",
    category: "Relacionamentos",
    intensity: "leve",
    text: "falar tanto do crush que o grupo decorou o nome?",
  },
  {
    id: "rel-008",
    category: "Relacionamentos",
    intensity: "leve",
    text: "esquecer a data de aniversário de namoro?",
  },
  {
    id: "rel-009",
    category: "Relacionamentos",
    intensity: "leve",
    text: "defender com a vida um casal de série que nem existe mais?",
  },
  {
    id: "rel-010",
    category: "Relacionamentos",
    intensity: "leve",
    text: "mandar áudio cantando pra quem ama?",
  },
  {
    id: "rel-011",
    category: "Relacionamentos",
    intensity: "leve",
    text: 'dizer "eu te amo" antes do primeiro mês?',
  },
  {
    id: "rel-012",
    category: "Relacionamentos",
    intensity: "leve",
    text: "montar playlist pro crush antes do primeiro encontro?",
  },
  {
    id: "rel-013",
    category: "Relacionamentos",
    intensity: "moderado",
    text: "ensaiar no espelho a conversa de terminar?",
  },
  {
    id: "rel-014",
    category: "Relacionamentos",
    intensity: "moderado",
    text: "curtir sem querer uma foto de 2016 do crush?",
  },
  {
    id: "rel-015",
    category: "Relacionamentos",
    intensity: "moderado",
    text: "pedir a opinião do grupo antes de responder o crush?",
  },
  {
    id: "rel-016",
    category: "Relacionamentos",
    intensity: "moderado",
    text: "voltar com o ex depois de jurar que não voltava?",
  },
  {
    id: "rel-017",
    category: "Relacionamentos",
    intensity: "moderado",
    text: "aparecer com alguém novo sem ter avisado nada ao grupo?",
  },
  {
    id: "rel-018",
    category: "Relacionamentos",
    intensity: "moderado",
    text: 'dizer que está solteiro estando "meio enrolado"?',
  },
  {
    id: "rel-019",
    category: "Relacionamentos",
    intensity: "moderado",
    text: "olhar o celular de minuto em minuto esperando resposta?",
  },
  {
    id: "rel-020",
    category: "Relacionamentos",
    intensity: "moderado",
    text: "fingir que ama o hobby do crush só pra ter assunto?",
  },
  {
    id: "rel-021",
    category: "Relacionamentos",
    intensity: "moderado",
    text: "apresentar alguém pra família cedo demais?",
  },
  {
    id: "rel-022",
    category: "Relacionamentos",
    intensity: "pesado",
    text: "continuar seguindo o ex e ver todos os stories?",
  },
  {
    id: "rel-023",
    category: "Relacionamentos",
    intensity: "pesado",
    text: "terminar por mensagem?",
  },
  {
    id: "rel-024",
    category: "Relacionamentos",
    intensity: "pesado",
    text: "chamar o ex no chat só porque uma música tocou?",
  },
  {
    id: "rel-025",
    category: "Relacionamentos",
    intensity: "pesado",
    text: "dar um perdido em alguém e chamar de novo como se nada tivesse acontecido?",
  },

  // Festa — festas, rolês, ressaca
  {
    id: "fes-001",
    category: "Festa",
    intensity: "leve",
    text: "dormir no sofá no meio da festa?",
  },
  {
    id: "fes-002",
    category: "Festa",
    intensity: "leve",
    text: "chegar primeiro e ajudar a arrumar tudo?",
  },
  {
    id: "fes-003",
    category: "Festa",
    intensity: "leve",
    text: "ser o último a ir embora?",
  },
  {
    id: "fes-004",
    category: "Festa",
    intensity: "leve",
    text: "assumir a caixa de som e não devolver mais?",
  },
  {
    id: "fes-005",
    category: "Festa",
    intensity: "leve",
    text: "perder o agasalho no rolê e nunca mais achar?",
  },
  {
    id: "fes-006",
    category: "Festa",
    intensity: "leve",
    text: "acabar com o salgadinho antes de todos chegarem?",
  },
  {
    id: "fes-007",
    category: "Festa",
    intensity: "leve",
    text: "tirar cem fotos e não postar nenhuma?",
  },
  {
    id: "fes-008",
    category: "Festa",
    intensity: "leve",
    text: "pedir comida de madrugada pra todo mundo?",
  },
  {
    id: "fes-009",
    category: "Festa",
    intensity: "leve",
    text: "abrir a pista dançando sozinho?",
  },
  {
    id: "fes-010",
    category: "Festa",
    intensity: "leve",
    text: "sumir da festa sem avisar ninguém?",
  },
  {
    id: "fes-011",
    category: "Festa",
    intensity: "leve",
    text: "marcar o churrasco e esquecer o carvão?",
  },
  {
    id: "fes-012",
    category: "Festa",
    intensity: "leve",
    text: "passar a noite no cantinho com o cachorro da casa?",
  },
  {
    id: "fes-013",
    category: "Festa",
    intensity: "moderado",
    text: "mandar mensagem de madrugada e se arrepender pela manhã?",
  },
  {
    id: "fes-014",
    category: "Festa",
    intensity: "moderado",
    text: "confirmar presença e cancelar em cima da hora?",
  },
  {
    id: "fes-015",
    category: "Festa",
    intensity: "moderado",
    text: "inventar uma desculpa para não ir num rolê?",
  },
  {
    id: "fes-016",
    category: "Festa",
    intensity: "moderado",
    text: "chamar o rolê pra sua casa sem avisar quem mora com você?",
  },
  {
    id: "fes-017",
    category: "Festa",
    intensity: "moderado",
    text: "pegar o microfone do karaokê sem saber a letra e não devolver?",
  },
  {
    id: "fes-018",
    category: "Festa",
    intensity: "moderado",
    text: "apagar a luz e ligar o modo balada sem ninguém pedir?",
  },
  {
    id: "fes-019",
    category: "Festa",
    intensity: "moderado",
    text: "dormir antes da meia-noite no Ano-Novo?",
  },
  {
    id: "fes-020",
    category: "Festa",
    intensity: "moderado",
    text: "ser o motorista da vez e cobrar isso pelo resto do ano?",
  },
  {
    id: "fes-021",
    category: "Festa",
    intensity: "moderado",
    text: "postar a foto em que só você ficou bem?",
  },
  {
    id: "fes-022",
    category: "Festa",
    intensity: "pesado",
    text: "postar a festa toda nos stories e apagar no dia seguinte?",
  },
  {
    id: "fes-023",
    category: "Festa",
    intensity: "pesado",
    text: "chamar o crush no fim da festa e ler a conversa com vergonha depois?",
  },
  {
    id: "fes-024",
    category: "Festa",
    intensity: "pesado",
    text: "contar no grupo o que rolou na festa antes de todos acordarem?",
  },
  {
    id: "fes-025",
    category: "Festa",
    intensity: "pesado",
    text: "jurar que não bebe mais e repetir a promessa todo mês?",
  },

  // Trabalho — nada acima de moderado
  {
    id: "tra-001",
    category: "Trabalho",
    intensity: "leve",
    text: "chegar atrasado na reunião de segunda?",
  },
  {
    id: "tra-002",
    category: "Trabalho",
    intensity: "leve",
    text: "responder e-mail em dois minutos?",
  },
  {
    id: "tra-003",
    category: "Trabalho",
    intensity: "leve",
    text: "esquecer o nome de alguém no primeiro dia?",
  },
  {
    id: "tra-004",
    category: "Trabalho",
    intensity: "leve",
    text: "levar bolo pro escritório sem motivo nenhum?",
  },
  {
    id: "tra-005",
    category: "Trabalho",
    intensity: "leve",
    text: "anotar tudo num papelzinho e perder o papelzinho?",
  },
  {
    id: "tra-006",
    category: "Trabalho",
    intensity: "leve",
    text: "ter cinquenta notificações não lidas no chat do time?",
  },
  {
    id: "tra-007",
    category: "Trabalho",
    intensity: "leve",
    text: "fazer café pra todo mundo antes da reunião?",
  },
  {
    id: "tra-008",
    category: "Trabalho",
    intensity: "leve",
    text: "marcar reunião de trinta minutos e usar cinco?",
  },
  {
    id: "tra-009",
    category: "Trabalho",
    intensity: "leve",
    text: "virar o especialista oficial em consertar a impressora?",
  },
  {
    id: "tra-010",
    category: "Trabalho",
    intensity: "leve",
    text: "enfeitar a mesa com bichinhos até não caber mais?",
  },
  {
    id: "tra-011",
    category: "Trabalho",
    intensity: "leve",
    text: "esquecer a marmita em casa?",
  },
  {
    id: "tra-012",
    category: "Trabalho",
    intensity: "leve",
    text: 'escrever "segue em anexo" e esquecer o anexo?',
  },
  {
    id: "tra-013",
    category: "Trabalho",
    intensity: "moderado",
    text: "entrar na reunião com a câmera sempre fechada?",
  },
  {
    id: "tra-014",
    category: "Trabalho",
    intensity: "moderado",
    text: "mandar mensagem de trabalho no domingo à noite?",
  },
  {
    id: "tra-015",
    category: "Trabalho",
    intensity: "moderado",
    text: 'dizer "vou dar uma olhada" e nunca dar?',
  },
  {
    id: "tra-016",
    category: "Trabalho",
    intensity: "moderado",
    text: "falar por último na reunião só pra repetir o que já foi dito?",
  },
  {
    id: "tra-017",
    category: "Trabalho",
    intensity: "moderado",
    text: 'responder "bom dia" às três da tarde?',
  },
  {
    id: "tra-018",
    category: "Trabalho",
    intensity: "moderado",
    text: "transformar um e-mail de duas linhas em três parágrafos?",
  },
  {
    id: "tra-019",
    category: "Trabalho",
    intensity: "moderado",
    text: "pedir pra remarcar a reunião cinco minutos antes?",
  },
  {
    id: "tra-020",
    category: "Trabalho",
    intensity: "moderado",
    text: 'usar "conforme alinhado" só pra lembrar que já tinha avisado?',
  },
  {
    id: "tra-021",
    category: "Trabalho",
    intensity: "moderado",
    text: "ficar no mudo e continuar falando por um minuto inteiro?",
  },
  {
    id: "tra-022",
    category: "Trabalho",
    intensity: "moderado",
    text: "dizer que a internet caiu pra sair da reunião?",
  },
  {
    id: "tra-023",
    category: "Trabalho",
    intensity: "moderado",
    text: "aceitar o prazo impossível e pedir mais uma semana depois?",
  },
  {
    id: "tra-024",
    category: "Trabalho",
    intensity: "moderado",
    text: "sair no horário exato, nem um minuto depois?",
  },
  {
    id: "tra-025",
    category: "Trabalho",
    intensity: "moderado",
    text: "criar um grupo novo pra um assunto que cabia numa mensagem?",
  },

  // Família — todas leve, roda com crianças na mesa
  {
    id: "fam-001",
    category: "Família",
    intensity: "leve",
    text: "esquecer o guarda-chuva em qualquer lugar?",
  },
  {
    id: "fam-002",
    category: "Família",
    intensity: "leve",
    text: "contar a mesma história de infância em todo almoço?",
  },
  {
    id: "fam-003",
    category: "Família",
    intensity: "leve",
    text: "mandar bom-dia com figurinha de flor no grupo da família?",
  },
  {
    id: "fam-004",
    category: "Família",
    intensity: "leve",
    text: "fotografar tudo que come na viagem?",
  },
  {
    id: "fam-005",
    category: "Família",
    intensity: "leve",
    text: "brigar pelo lugar da janela no carro?",
  },
  {
    id: "fam-006",
    category: "Família",
    intensity: "leve",
    text: "dormir no sofá vendo o jornal?",
  },
  {
    id: "fam-007",
    category: "Família",
    intensity: "leve",
    text: "guardar pote de sorvete vazio pra usar de vasilha?",
  },
  {
    id: "fam-008",
    category: "Família",
    intensity: "leve",
    text: "perguntar a mesma coisa três vezes na ligação?",
  },
  {
    id: "fam-009",
    category: "Família",
    intensity: "leve",
    text: "dar nome pra cada planta da casa?",
  },
  {
    id: "fam-010",
    category: "Família",
    intensity: "leve",
    text: "querer servir o prato de todo mundo?",
  },
  {
    id: "fam-011",
    category: "Família",
    intensity: "leve",
    text: "cantar no banho e a casa toda ouvir?",
  },
  {
    id: "fam-012",
    category: "Família",
    intensity: "leve",
    text: "perder o controle da TV entre as almofadas?",
  },
  {
    id: "fam-013",
    category: "Família",
    intensity: "leve",
    text: "chorar assistindo desenho animado?",
  },
  {
    id: "fam-014",
    category: "Família",
    intensity: "leve",
    text: "trazer lembrancinha de viagem pra todo mundo?",
  },
  {
    id: "fam-015",
    category: "Família",
    intensity: "leve",
    text: "ser o primeiro a acordar no domingo?",
  },
  {
    id: "fam-016",
    category: "Família",
    intensity: "leve",
    text: "esquecer a panela no fogo e sair correndo pra cozinha?",
  },
  {
    id: "fam-017",
    category: "Família",
    intensity: "leve",
    text: "juntar todos os parentes pra uma foto?",
  },
  {
    id: "fam-018",
    category: "Família",
    intensity: "leve",
    text: "adotar mais um cachorro sem avisar ninguém?",
  },
  {
    id: "fam-019",
    category: "Família",
    intensity: "leve",
    text: "discutir com a família pela velocidade do ventilador?",
  },
  {
    id: "fam-020",
    category: "Família",
    intensity: "leve",
    text: "guardar o presente de Natal no armário e esquecer de dar?",
  },
  {
    id: "fam-021",
    category: "Família",
    intensity: "leve",
    text: "montar o quebra-cabeça de mil peças até o fim?",
  },
  {
    id: "fam-022",
    category: "Família",
    intensity: "leve",
    text: "perder no jogo de tabuleiro e pedir revanche na hora?",
  },
  {
    id: "fam-023",
    category: "Família",
    intensity: "leve",
    text: "querer escolher o filme da sessão de sábado?",
  },
  {
    id: "fam-024",
    category: "Família",
    intensity: "leve",
    text: 'passar a receita usando só medidas "a olho"?',
  },
  {
    id: "fam-025",
    category: "Família",
    intensity: "leve",
    text: "errar o caminho e insistir que é atalho?",
  },

  // Futebol — pelada, torcida, futebol
  {
    id: "fut-001",
    category: "Futebol",
    intensity: "leve",
    text: "chegar com chuteira nova e não jogar nada?",
  },
  {
    id: "fut-002",
    category: "Futebol",
    intensity: "leve",
    text: "se oferecer pra ser goleiro só pra não correr?",
  },
  {
    id: "fut-003",
    category: "Futebol",
    intensity: "leve",
    text: "comemorar gol de pelada como se fosse final?",
  },
  {
    id: "fut-004",
    category: "Futebol",
    intensity: "leve",
    text: "levar a bola e ir embora com ela?",
  },
  {
    id: "fut-005",
    category: "Futebol",
    intensity: "leve",
    text: "vestir a mesma camisa em todo jogo por superstição?",
  },
  {
    id: "fut-006",
    category: "Futebol",
    intensity: "leve",
    text: "esquecer o meião e jogar de tênis de corrida?",
  },
  {
    id: "fut-007",
    category: "Futebol",
    intensity: "leve",
    text: "querer ser o camisa 10 e nunca passar a bola?",
  },
  {
    id: "fut-008",
    category: "Futebol",
    intensity: "leve",
    text: "marcar a pelada e chegar por último?",
  },
  {
    id: "fut-009",
    category: "Futebol",
    intensity: "leve",
    text: "gritar com a TV como se o jogador escutasse?",
  },
  {
    id: "fut-010",
    category: "Futebol",
    intensity: "leve",
    text: "sentar sempre no mesmo lugar pro time não perder?",
  },
  {
    id: "fut-011",
    category: "Futebol",
    intensity: "leve",
    text: "pedir pênalti em absolutamente tudo?",
  },
  {
    id: "fut-012",
    category: "Futebol",
    intensity: "leve",
    text: "faltar no sorteio dos times e reclamar do resultado?",
  },
  {
    id: "fut-013",
    category: "Futebol",
    intensity: "moderado",
    text: "cair na área pedindo falta que não teve?",
  },
  {
    id: "fut-014",
    category: "Futebol",
    intensity: "moderado",
    text: "discutir com o juiz da pelada sendo que o juiz é seu amigo?",
  },
  {
    id: "fut-015",
    category: "Futebol",
    intensity: "moderado",
    text: "arrumar desculpa pra sair mais cedo quando o time está perdendo?",
  },
  {
    id: "fut-016",
    category: "Futebol",
    intensity: "moderado",
    text: "provocar o grupo inteiro depois de uma vitória magra?",
  },
  {
    id: "fut-017",
    category: "Futebol",
    intensity: "moderado",
    text: "dizer que o time não joga mais nada e voltar a elogiar na semana seguinte?",
  },
  {
    id: "fut-018",
    category: "Futebol",
    intensity: "moderado",
    text: "se escalar como titular na frente de quem joga melhor?",
  },
  {
    id: "fut-019",
    category: "Futebol",
    intensity: "moderado",
    text: "prometer que vai treinar e aparecer só no dia do jogo?",
  },
  {
    id: "fut-020",
    category: "Futebol",
    intensity: "moderado",
    text: "cobrar todas as faltas e nunca acertar o gol?",
  },
  {
    id: "fut-021",
    category: "Futebol",
    intensity: "moderado",
    text: "sumir do grupo da pelada na semana em que é sua vez de levar a água?",
  },
  {
    id: "fut-022",
    category: "Futebol",
    intensity: "pesado",
    text: "torcer contra o time do melhor amigo?",
  },
  {
    id: "fut-023",
    category: "Futebol",
    intensity: "pesado",
    text: "perder a aposta da rodada e nunca cumprir o combinado?",
  },
  {
    id: "fut-024",
    category: "Futebol",
    intensity: "pesado",
    text: "trocar de time do coração e negar que trocou?",
  },
  {
    id: "fut-025",
    category: "Futebol",
    intensity: "pesado",
    text: "lembrar até hoje daquele gol que alguém do grupo perdeu?",
  },
];
