import type { PerfectQuestion } from './perfect-types';

/**
 * Banco de perguntas do "Casal Perfeito".
 *
 * A régua: a pergunta é boa quando os dois conseguem responder em cinco segundos e a resposta
 * rende conversa na mesa. Pergunta que exige lembrar uma data exata não rende — rende discussão
 * sobre memória, que é outra coisa.
 *
 * Segurança (§59) — o jogo é jogado na frente dos outros casais, e ninguém escolheu terapia em
 * grupo. Nada de traição, término, ex, fertilidade, gravidez, sexo explícito, dívida, saúde,
 * trauma, aparência, segredo ou comparação com outro parceiro. Nenhuma pergunta cujo caminho
 * honesto termine em briga: "quem se irrita mais rápido" é brincadeira, "o que te decepciona
 * nele" é uma noite estragada.
 *
 * `Casal` é a única categoria provocativa, e não entra sem o host marcar.
 *
 * As mecânicas estão misturadas de propósito dentro de cada categoria: uma partida que caísse só
 * em "quem é mais" viraria a mesma pergunta vinte vezes.
 */
export const QUESTIONS: PerfectQuestion[] = [
  /* ─────────────────────────────────────────────────────── 😂 Dia a dia ── */
  { id: 'dia-001', category: 'Dia a dia', type: 'who', text: 'Quem demora mais para se arrumar?' },
  { id: 'dia-002', category: 'Dia a dia', type: 'who', text: 'Quem dorme primeiro?' },
  { id: 'dia-003', category: 'Dia a dia', type: 'who', text: 'Quem mais esquece onde deixou as coisas?' },
  { id: 'dia-004', category: 'Dia a dia', type: 'who', text: 'Quem decide o que vocês vão assistir?' },
  { id: 'dia-005', category: 'Dia a dia', type: 'who', text: 'Quem pede comida com mais frequência?' },
  { id: 'dia-006', category: 'Dia a dia', type: 'who', text: 'Quem acorda de melhor humor?' },
  { id: 'dia-007', category: 'Dia a dia', type: 'who', text: 'Quem fala mais ao telefone?' },
  { id: 'dia-008', category: 'Dia a dia', type: 'who', text: 'Quem é mais organizado?' },
  { id: 'dia-009', category: 'Dia a dia', type: 'who', text: 'Quem se atrasa mais?' },
  { id: 'dia-010', category: 'Dia a dia', type: 'who', text: 'Quem canta mais alto no carro?' },
  { id: 'dia-011', category: 'Dia a dia', type: 'who', text: 'Quem passa mais tempo no celular?' },
  { id: 'dia-012', category: 'Dia a dia', type: 'who', text: 'Quem é mais teimoso numa discussão boba?' },
  { id: 'dia-013', category: 'Dia a dia', type: 'who', text: 'Quem lembra dos aniversários da família?' },
  { id: 'dia-014', category: 'Dia a dia', type: 'who', text: 'Quem toma banho mais demorado?' },
  { id: 'dia-015', category: 'Dia a dia', type: 'who', text: 'Quem reclama mais do trânsito?' },
  {
    id: 'dia-016',
    category: 'Dia a dia',
    type: 'same',
    text: 'Sexta à noite, sem plano nenhum. O que vocês escolheriam?',
    options: [
      { id: 'casa', emoji: '🍕', label: 'Pedir comida e ficar em casa' },
      { id: 'sair', emoji: '🎉', label: 'Sair' },
      { id: 'cinema', emoji: '🎬', label: 'Cinema' },
      { id: 'amigos', emoji: '🍻', label: 'Chamar os amigos' },
    ],
  },
  {
    id: 'dia-017',
    category: 'Dia a dia',
    type: 'same',
    text: 'Domingo de manhã na casa de vocês é mais:',
    options: [
      { id: 'dormir', emoji: '😴', label: 'Dormir até tarde' },
      { id: 'cafe', emoji: '☕', label: 'Café demorado' },
      { id: 'rua', emoji: '🚶', label: 'Sair cedo para algum lugar' },
      { id: 'faxina', emoji: '🧹', label: 'Arrumar a casa' },
    ],
  },
  {
    id: 'dia-018',
    category: 'Dia a dia',
    type: 'same',
    text: 'A discussão mais frequente de vocês é sobre:',
    options: [
      { id: 'louca', emoji: '🍽', label: 'Louça e bagunça' },
      { id: 'atraso', emoji: '⏰', label: 'Horário' },
      { id: 'tv', emoji: '📺', label: 'O que assistir' },
      { id: 'temperatura', emoji: '🌡', label: 'Ar-condicionado e ventilador' },
    ],
  },
  { id: 'dia-019', category: 'Dia a dia', type: 'scale', text: 'De 1 a 5, quanto vocês gostam de acordar cedo?', scale: { low: 'de jeito nenhum', high: 'amamos' } },
  { id: 'dia-020', category: 'Dia a dia', type: 'scale', text: 'De 1 a 5, quanto a casa de vocês costuma estar arrumada?', scale: { low: 'um caos', high: 'impecável' } },

  /* ───────────────────────────────────────────────── ❤️ Relacionamento ── */
  { id: 'rel-001', category: 'Relacionamento', type: 'who', text: 'Quem disse "eu te amo" primeiro?' },
  { id: 'rel-002', category: 'Relacionamento', type: 'who', text: 'Quem tomou a iniciativa no primeiro beijo?' },
  { id: 'rel-003', category: 'Relacionamento', type: 'who', text: 'Quem é mais romântico?' },
  { id: 'rel-004', category: 'Relacionamento', type: 'who', text: 'Quem costuma pedir desculpas primeiro?' },
  { id: 'rel-005', category: 'Relacionamento', type: 'who', text: 'Quem manda mais mensagem durante o dia?' },
  { id: 'rel-006', category: 'Relacionamento', type: 'who', text: 'Quem é mais ciumento?' },
  { id: 'rel-007', category: 'Relacionamento', type: 'who', text: 'Quem planeja as surpresas?' },
  { id: 'rel-008', category: 'Relacionamento', type: 'who', text: 'Quem ri mais das próprias piadas?' },
  { id: 'rel-009', category: 'Relacionamento', type: 'who', text: 'Quem chora mais num filme?' },
  { id: 'rel-010', category: 'Relacionamento', type: 'who', text: 'Quem elogia mais o outro em público?' },
  { id: 'rel-011', category: 'Relacionamento', type: 'who', text: 'Quem dá o melhor presente?' },
  { id: 'rel-012', category: 'Relacionamento', type: 'who', text: 'Quem cede mais rápido quando os dois querem coisas diferentes?' },
  {
    id: 'rel-013',
    category: 'Relacionamento',
    type: 'same',
    text: 'O jeito mais garantido de melhorar o dia do outro é:',
    options: [
      { id: 'comida', emoji: '🍫', label: 'Aparecer com comida' },
      { id: 'abraco', emoji: '🤗', label: 'Um abraço demorado' },
      { id: 'ouvir', emoji: '👂', label: 'Ouvir sem interromper' },
      { id: 'resolver', emoji: '🛠', label: 'Resolver alguma coisa chata para o outro' },
    ],
  },
  {
    id: 'rel-014',
    category: 'Relacionamento',
    type: 'same',
    text: 'Um date à noite, os dois cansados. Vocês escolheriam:',
    options: [
      { id: 'jantar', emoji: '🍽', label: 'Jantar fora' },
      { id: 'sofa', emoji: '🛋', label: 'Sofá e série' },
      { id: 'caminhar', emoji: '🌙', label: 'Caminhar sem destino' },
      { id: 'cozinhar', emoji: '👩‍🍳', label: 'Cozinhar juntos' },
    ],
  },
  { id: 'rel-015', category: 'Relacionamento', type: 'scale', text: 'De 1 a 5, quanto vocês são de demonstrar carinho em público?', scale: { low: 'nada', high: 'sem freio' } },
  { id: 'rel-016', category: 'Relacionamento', type: 'scale', text: 'De 1 a 5, quanto vocês gostam de comemorar datas?', scale: { low: 'passa batido', high: 'é sagrado' } },
  {
    id: 'rel-017',
    category: 'Relacionamento',
    type: 'know',
    text: 'Qual desses te deixa mais feliz de receber?',
    predictText: 'O que deixa {nome} mais feliz de receber?',
    options: [
      { id: 'presente', emoji: '🎁', label: 'Um presente pensado' },
      { id: 'tempo', emoji: '⏳', label: 'Tempo junto, sem pressa' },
      { id: 'palavra', emoji: '💬', label: 'Um elogio sincero' },
      { id: 'ajuda', emoji: '🤝', label: 'Uma ajuda sem precisar pedir' },
    ],
  },
  {
    id: 'rel-018',
    category: 'Relacionamento',
    type: 'know',
    text: 'Depois de um dia horrível, o que você prefere?',
    predictText: 'Depois de um dia horrível, o que {nome} prefere?',
    options: [
      { id: 'falar', emoji: '🗣', label: 'Falar sobre o assunto' },
      { id: 'silencio', emoji: '🤐', label: 'Ficar quieto um pouco' },
      { id: 'distrair', emoji: '🎮', label: 'Se distrair com outra coisa' },
      { id: 'colo', emoji: '🫂', label: 'Um colo e nada de conversa' },
    ],
  },

  /* ───────────────────────────────────────────── 👀 Quem conhece melhor ── */
  {
    id: 'con-001',
    category: 'Quem conhece melhor',
    type: 'know',
    text: 'Qual sobremesa você escolheria?',
    predictText: 'Qual sobremesa {nome} escolheria?',
    options: [
      { id: 'chocolate', emoji: '🍫', label: 'Chocolate' },
      { id: 'sorvete', emoji: '🍨', label: 'Sorvete' },
      { id: 'bolo', emoji: '🍰', label: 'Bolo' },
      { id: 'pudim', emoji: '🍮', label: 'Pudim' },
    ],
  },
  {
    id: 'con-002',
    category: 'Quem conhece melhor',
    type: 'know',
    text: 'Um sábado livre inteiro só para você. Você faria o quê?',
    predictText: 'Um sábado livre inteiro só para {nome}. O que essa pessoa faria?',
    options: [
      { id: 'dormir', emoji: '😴', label: 'Dormir e não fazer nada' },
      { id: 'amigos', emoji: '🍻', label: 'Ver os amigos' },
      { id: 'hobby', emoji: '🎨', label: 'Se enfiar num hobby' },
      { id: 'rua', emoji: '🏃', label: 'Sair para se mexer' },
    ],
  },
  {
    id: 'con-003',
    category: 'Quem conhece melhor',
    type: 'know',
    text: 'Qual desses te irrita mais?',
    predictText: 'Qual desses irrita mais {nome}?',
    options: [
      { id: 'atraso', emoji: '⏰', label: 'Gente atrasada' },
      { id: 'barulho', emoji: '🔊', label: 'Barulho demais' },
      { id: 'fila', emoji: '🧍', label: 'Fila' },
      { id: 'mastigar', emoji: '😬', label: 'Barulho de mastigar' },
    ],
  },
  {
    id: 'con-004',
    category: 'Quem conhece melhor',
    type: 'know',
    text: 'Numa noite de festa, você é mais:',
    predictText: 'Numa noite de festa, {nome} é mais:',
    options: [
      { id: 'primeiro', emoji: '🕺', label: 'O primeiro a dançar' },
      { id: 'conversa', emoji: '💬', label: 'Na conversa do canto' },
      { id: 'comida', emoji: '🍢', label: 'Perto da comida' },
      { id: 'embora', emoji: '🚪', label: 'O primeiro a sumir' },
    ],
  },
  {
    id: 'con-005',
    category: 'Quem conhece melhor',
    type: 'know',
    text: 'Qual bicho você levaria para casa hoje?',
    predictText: 'Qual bicho {nome} levaria para casa hoje?',
    options: [
      { id: 'cachorro', emoji: '🐶', label: 'Cachorro' },
      { id: 'gato', emoji: '🐱', label: 'Gato' },
      { id: 'nenhum', emoji: '🚫', label: 'Nenhum, obrigado' },
      { id: 'exotico', emoji: '🦎', label: 'Algo bem diferente' },
    ],
  },
  {
    id: 'con-006',
    category: 'Quem conhece melhor',
    type: 'know',
    text: 'Você prefere um fim de semana:',
    predictText: '{nome} prefere um fim de semana:',
    options: [
      { id: 'cheio', emoji: '📅', label: 'Cheio de plano' },
      { id: 'vazio', emoji: '🫗', label: 'Sem nenhum plano' },
      { id: 'meio', emoji: '⚖️', label: 'Um plano só, o resto livre' },
    ],
  },
  {
    id: 'con-007',
    category: 'Quem conhece melhor',
    type: 'know',
    text: 'Qual desses você faria de novo sem pensar?',
    predictText: 'Qual desses {nome} faria de novo sem pensar?',
    options: [
      { id: 'show', emoji: '🎤', label: 'Um show' },
      { id: 'viagem', emoji: '🧳', label: 'Uma viagem' },
      { id: 'restaurante', emoji: '🍝', label: 'Um restaurante' },
      { id: 'dia', emoji: '🌤', label: 'Um dia inteiro sem fazer nada' },
    ],
  },
  {
    id: 'con-008',
    category: 'Quem conhece melhor',
    type: 'know',
    text: 'Seu jeito de descansar é:',
    predictText: 'O jeito de {nome} descansar é:',
    options: [
      { id: 'tela', emoji: '📺', label: 'Série ou filme' },
      { id: 'sono', emoji: '🛏', label: 'Dormir' },
      { id: 'fora', emoji: '🌳', label: 'Sair de casa' },
      { id: 'maos', emoji: '🧩', label: 'Fazer algo com as mãos' },
    ],
  },
  {
    id: 'con-009',
    category: 'Quem conhece melhor',
    type: 'know',
    text: 'Numa discussão, você:',
    predictText: 'Numa discussão, {nome}:',
    options: [
      { id: 'fala', emoji: '🗣', label: 'Fala na hora' },
      { id: 'pensa', emoji: '🤔', label: 'Precisa de um tempo' },
      { id: 'piada', emoji: '😅', label: 'Faz piada para aliviar' },
      { id: 'cede', emoji: '🕊', label: 'Cede para acabar logo' },
    ],
  },
  {
    id: 'con-010',
    category: 'Quem conhece melhor',
    type: 'know',
    text: 'Qual desses lugares você escolheria para morar?',
    predictText: 'Qual desses lugares {nome} escolheria para morar?',
    options: [
      { id: 'cidade', emoji: '🏙', label: 'Cidade grande' },
      { id: 'praia', emoji: '🏖', label: 'Litoral' },
      { id: 'interior', emoji: '🌾', label: 'Interior' },
      { id: 'fora', emoji: '🌍', label: 'Outro país' },
    ],
  },
  {
    id: 'con-011',
    category: 'Quem conhece melhor',
    type: 'know',
    text: 'O que você faria primeiro num dia de folga inesperada?',
    predictText: 'O que {nome} faria primeiro num dia de folga inesperada?',
    options: [
      { id: 'dormir', emoji: '😴', label: 'Voltar a dormir' },
      { id: 'pendencia', emoji: '✅', label: 'Resolver uma pendência' },
      { id: 'passear', emoji: '🚗', label: 'Sair para passear' },
      { id: 'chamar', emoji: '📞', label: 'Chamar alguém' },
    ],
  },
  {
    id: 'con-012',
    category: 'Quem conhece melhor',
    type: 'know',
    text: 'Seu tipo de filme é:',
    predictText: 'O tipo de filme de {nome} é:',
    options: [
      { id: 'comedia', emoji: '😂', label: 'Comédia' },
      { id: 'acao', emoji: '💥', label: 'Ação' },
      { id: 'terror', emoji: '👻', label: 'Terror' },
      { id: 'drama', emoji: '🎭', label: 'Drama' },
    ],
  },
  { id: 'con-013', category: 'Quem conhece melhor', type: 'scale', text: 'De 1 a 5, quanto você se considera uma pessoa paciente?', scale: { low: 'nada', high: 'muito' } },
  { id: 'con-014', category: 'Quem conhece melhor', type: 'scale', text: 'De 1 a 5, quanto você gosta de ser o centro das atenções?', scale: { low: 'odeio', high: 'adoro' } },
  { id: 'con-015', category: 'Quem conhece melhor', type: 'scale', text: 'De 1 a 5, quanto você é bom de cozinha?', scale: { low: 'queimo água', high: 'sou chef' } },
  { id: 'con-016', category: 'Quem conhece melhor', type: 'scale', text: 'De 1 a 5, quanto você consegue guardar segredo?', scale: { low: 'conto tudo', high: 'vou ao túmulo' } },
  { id: 'con-017', category: 'Quem conhece melhor', type: 'who', text: 'Quem conhece melhor os amigos do outro?' },
  { id: 'con-018', category: 'Quem conhece melhor', type: 'who', text: 'Quem sabe de cor o pedido do outro no restaurante?' },
  { id: 'con-019', category: 'Quem conhece melhor', type: 'who', text: 'Quem percebe primeiro quando o outro está estranho?' },
  { id: 'con-020', category: 'Quem conhece melhor', type: 'who', text: 'Quem é melhor em escolher presente para o outro?' },
  /* ─────────────────────────────────────────────────── 🕰 Nossa história ── */
  { id: 'his-001', category: 'Nossa história', type: 'who', text: 'Quem chamou quem para sair primeiro?' },
  { id: 'his-002', category: 'Nossa história', type: 'who', text: 'Quem estava mais nervoso no primeiro encontro?' },
  { id: 'his-003', category: 'Nossa história', type: 'who', text: 'Quem contou primeiro para os amigos sobre o outro?' },
  { id: 'his-004', category: 'Nossa história', type: 'who', text: 'Quem demorou mais para responder as primeiras mensagens?' },
  { id: 'his-005', category: 'Nossa história', type: 'who', text: 'Quem lembra mais detalhes do começo de vocês?' },
  {
    id: 'his-006',
    category: 'Nossa história',
    type: 'same',
    text: 'O primeiro programa de vocês juntos foi mais parecido com:',
    options: [
      { id: 'comer', emoji: '🍽', label: 'Comer alguma coisa' },
      { id: 'bar', emoji: '🍻', label: 'Um bar' },
      { id: 'passeio', emoji: '🚶', label: 'Um passeio' },
      { id: 'casa', emoji: '🏠', label: 'Ficar em casa' },
    ],
  },
  {
    id: 'his-007',
    category: 'Nossa história',
    type: 'same',
    text: 'Vocês se conheceram:',
    options: [
      { id: 'amigos', emoji: '👥', label: 'Por amigos em comum' },
      { id: 'app', emoji: '📱', label: 'Pela internet' },
      { id: 'trabalho', emoji: '💼', label: 'Trabalho ou estudo' },
      { id: 'acaso', emoji: '🎲', label: 'Por acaso, na rua' },
    ],
  },
  {
    id: 'his-008',
    category: 'Nossa história',
    type: 'same',
    text: 'A primeira viagem de vocês foi:',
    options: [
      { id: 'praia', emoji: '🏖', label: 'Praia' },
      { id: 'estrada', emoji: '🚗', label: 'Estrada, perto' },
      { id: 'longe', emoji: '✈️', label: 'Longe' },
      { id: 'ainda', emoji: '⏳', label: 'Ainda não rolou' },
    ],
  },
  {
    id: 'his-009',
    category: 'Nossa história',
    type: 'same',
    text: 'O começo de vocês foi:',
    options: [
      { id: 'rapido', emoji: '⚡', label: 'Rápido, engatou de uma vez' },
      { id: 'devagar', emoji: '🐢', label: 'Devagar, foi acontecendo' },
      { id: 'idas', emoji: '🔄', label: 'Com idas e vindas' },
      { id: 'amizade', emoji: '🤝', label: 'Começou como amizade' },
    ],
  },
  {
    id: 'his-010',
    category: 'Nossa história',
    type: 'same',
    text: 'A música que mais tem a ver com vocês seria:',
    options: [
      { id: 'romantica', emoji: '🎻', label: 'Uma bem romântica' },
      { id: 'animada', emoji: '🎉', label: 'Uma animada' },
      { id: 'sertanejo', emoji: '🤠', label: 'Um sertanejo' },
      { id: 'nenhuma', emoji: '🤷', label: 'Nenhuma, vocês não têm música' },
    ],
  },
  {
    id: 'his-011',
    category: 'Nossa história',
    type: 'same',
    text: 'A história que vocês mais contam para os outros é sobre:',
    options: [
      { id: 'conhecer', emoji: '💘', label: 'Como se conheceram' },
      { id: 'viagem', emoji: '🧳', label: 'Uma viagem' },
      { id: 'perrengue', emoji: '😅', label: 'Um perrengue' },
      { id: 'festa', emoji: '🎊', label: 'Uma festa' },
    ],
  },
  { id: 'his-012', category: 'Nossa história', type: 'scale', text: 'De 1 a 5, quanto vocês contam a mesma história do mesmo jeito?', scale: { low: 'nunca bate', high: 'igualzinho' } },
  {
    id: 'his-013',
    category: 'Nossa história',
    type: 'know',
    text: 'Qual momento de vocês você guardaria numa foto só?',
    predictText: 'Qual momento de vocês {nome} guardaria numa foto só?',
    options: [
      { id: 'primeiro', emoji: '💘', label: 'O primeiro encontro' },
      { id: 'viagem', emoji: '🧳', label: 'Uma viagem' },
      { id: 'comum', emoji: '🛋', label: 'Um dia comum em casa' },
      { id: 'festa', emoji: '🎊', label: 'Uma comemoração' },
    ],
  },
  { id: 'his-014', category: 'Nossa história', type: 'who', text: 'Quem puxa mais assunto sobre o começo de vocês?' },

  /* ───────────────────────────────────────────────────────── ✈️ Viagens ── */
  {
    id: 'via-001',
    category: 'Viagens',
    type: 'same',
    text: 'Se vocês pudessem viajar amanhã, seria para:',
    options: [
      { id: 'praia', emoji: '🏖', label: 'Praia' },
      { id: 'montanha', emoji: '🏔', label: 'Montanha' },
      { id: 'cidade', emoji: '🏙', label: 'Cidade grande' },
      { id: 'natureza', emoji: '🌲', label: 'Natureza' },
    ],
  },
  {
    id: 'via-002',
    category: 'Viagens',
    type: 'same',
    text: 'A viagem dos sonhos de vocês seria:',
    options: [
      { id: 'resort', emoji: '🏝', label: 'Resort, sem fazer nada' },
      { id: 'roadtrip', emoji: '🚗', label: 'Road trip' },
      { id: 'pais', emoji: '✈️', label: 'Outro país' },
      { id: 'aventura', emoji: '🥾', label: 'Aventura' },
    ],
  },
  {
    id: 'via-003',
    category: 'Viagens',
    type: 'same',
    text: 'Numa viagem, vocês preferem:',
    options: [
      { id: 'roteiro', emoji: '🗺', label: 'Roteiro fechado' },
      { id: 'improviso', emoji: '🎲', label: 'Decidir na hora' },
      { id: 'misto', emoji: '⚖️', label: 'Um pouco de cada' },
    ],
  },
  {
    id: 'via-004',
    category: 'Viagens',
    type: 'same',
    text: 'O melhor jeito de conhecer um lugar novo é:',
    options: [
      { id: 'comer', emoji: '🍜', label: 'Comendo' },
      { id: 'andar', emoji: '🚶', label: 'Andando sem rumo' },
      { id: 'pontos', emoji: '📸', label: 'Pelos pontos famosos' },
      { id: 'gente', emoji: '🗣', label: 'Conversando com as pessoas' },
    ],
  },
  { id: 'via-005', category: 'Viagens', type: 'who', text: 'Quem arruma a mala primeiro?' },
  { id: 'via-006', category: 'Viagens', type: 'who', text: 'Quem esquece alguma coisa em casa?' },
  { id: 'via-007', category: 'Viagens', type: 'who', text: 'Quem quer chegar cedo demais no aeroporto?' },
  { id: 'via-008', category: 'Viagens', type: 'who', text: 'Quem tira mais foto?' },
  { id: 'via-009', category: 'Viagens', type: 'who', text: 'Quem decide onde vocês vão comer na viagem?' },
  { id: 'via-010', category: 'Viagens', type: 'who', text: 'Quem dorme primeiro no avião ou no ônibus?' },
  { id: 'via-011', category: 'Viagens', type: 'scale', text: 'De 1 a 5, quanto vocês gostam de planejar viagem com antecedência?', scale: { low: 'decidimos na hora', high: 'planilha pronta' } },
  { id: 'via-012', category: 'Viagens', type: 'scale', text: 'De 1 a 5, quanto vocês topariam uma viagem de última hora?', scale: { low: 'nem pensar', high: 'já arrumei a mala' } },
  {
    id: 'via-013',
    category: 'Viagens',
    type: 'know',
    text: 'Na viagem, o que você não abre mão?',
    predictText: 'Na viagem, de que {nome} não abre mão?',
    options: [
      { id: 'cama', emoji: '🛏', label: 'Uma cama boa' },
      { id: 'comida', emoji: '🍽', label: 'Comer bem' },
      { id: 'passeio', emoji: '🎟', label: 'Ver tudo' },
      { id: 'descanso', emoji: '😌', label: 'Não ter hora para nada' },
    ],
  },
  {
    id: 'via-014',
    category: 'Viagens',
    type: 'know',
    text: 'Você prefere voltar para um lugar que ama ou conhecer um novo?',
    predictText: '{nome} prefere voltar para um lugar que ama ou conhecer um novo?',
    options: [
      { id: 'voltar', emoji: '🔁', label: 'Voltar para o de sempre' },
      { id: 'novo', emoji: '🆕', label: 'Conhecer um novo' },
    ],
  },

  /* ────────────────────────────────────────────────────────── 🍔 Comida ── */
  {
    id: 'com-001',
    category: 'Comida',
    type: 'same',
    text: 'O jantar de hoje seria:',
    options: [
      { id: 'pizza', emoji: '🍕', label: 'Pizza' },
      { id: 'hamburguer', emoji: '🍔', label: 'Hambúrguer' },
      { id: 'japones', emoji: '🍣', label: 'Japonês' },
      { id: 'massa', emoji: '🍝', label: 'Massa' },
    ],
  },
  {
    id: 'com-002',
    category: 'Comida',
    type: 'same',
    text: 'O café da manhã perfeito de vocês tem:',
    options: [
      { id: 'pao', emoji: '🥖', label: 'Pão na chapa' },
      { id: 'doce', emoji: '🥐', label: 'Alguma coisa doce' },
      { id: 'ovo', emoji: '🍳', label: 'Ovos' },
      { id: 'fruta', emoji: '🍉', label: 'Fruta e café' },
    ],
  },
  {
    id: 'com-003',
    category: 'Comida',
    type: 'same',
    text: 'Sobremesa para dividir:',
    options: [
      { id: 'chocolate', emoji: '🍫', label: 'Chocolate' },
      { id: 'sorvete', emoji: '🍨', label: 'Sorvete' },
      { id: 'pudim', emoji: '🍮', label: 'Pudim' },
      { id: 'nada', emoji: '🙅', label: 'Nada, estamos cheios' },
    ],
  },
  {
    id: 'com-004',
    category: 'Comida',
    type: 'same',
    text: 'Domingo de almoço em família:',
    options: [
      { id: 'churrasco', emoji: '🍖', label: 'Churrasco' },
      { id: 'macarrao', emoji: '🍝', label: 'Macarronada' },
      { id: 'feijoada', emoji: '🥘', label: 'Feijoada' },
      { id: 'rua', emoji: '🍽', label: 'Comer fora' },
    ],
  },
  { id: 'com-005', category: 'Comida', type: 'who', text: 'Quem cozinha melhor?' },
  { id: 'com-006', category: 'Comida', type: 'who', text: 'Quem come mais rápido?' },
  { id: 'com-007', category: 'Comida', type: 'who', text: 'Quem rouba comida do prato do outro?' },
  { id: 'com-008', category: 'Comida', type: 'who', text: 'Quem demora mais para escolher no cardápio?' },
  { id: 'com-009', category: 'Comida', type: 'who', text: 'Quem é mais chato para comer?' },
  { id: 'com-010', category: 'Comida', type: 'who', text: 'Quem lava a louça depois?' },
  {
    id: 'com-011',
    category: 'Comida',
    type: 'know',
    text: 'Qual desses você nunca recusa?',
    predictText: 'Qual desses {nome} nunca recusa?',
    options: [
      { id: 'salgado', emoji: '🥟', label: 'Um salgado' },
      { id: 'doce', emoji: '🍩', label: 'Um doce' },
      { id: 'cafe', emoji: '☕', label: 'Um café' },
      { id: 'fritas', emoji: '🍟', label: 'Batata frita' },
    ],
  },
  {
    id: 'com-012',
    category: 'Comida',
    type: 'know',
    text: 'Se só desse para comer uma coisa pelo resto do mês:',
    predictText: 'Se {nome} só pudesse comer uma coisa pelo resto do mês:',
    options: [
      { id: 'pizza', emoji: '🍕', label: 'Pizza' },
      { id: 'arroz', emoji: '🍚', label: 'Arroz com feijão' },
      { id: 'lanche', emoji: '🥪', label: 'Lanche' },
      { id: 'massa', emoji: '🍝', label: 'Massa' },
    ],
  },
  { id: 'com-013', category: 'Comida', type: 'scale', text: 'De 1 a 5, quanto vocês gostam de pimenta?', scale: { low: 'zero', high: 'quanto mais melhor' } },
  { id: 'com-014', category: 'Comida', type: 'scale', text: 'De 1 a 5, quanto vocês topam experimentar comida estranha?', scale: { low: 'nem morto', high: 'topamos tudo' } },

  /* ───────────────────────────────────────────────────────── 💰 Dinheiro ── */
  {
    id: 'din-001',
    category: 'Dinheiro',
    type: 'same',
    text: 'Se caíssem dez mil reais do céu, o primeiro destino seria:',
    options: [
      { id: 'viagem', emoji: '✈️', label: 'Viagem' },
      { id: 'guardar', emoji: '🏦', label: 'Guardar' },
      { id: 'casa', emoji: '🏠', label: 'Alguma coisa para casa' },
      { id: 'gastar', emoji: '🛍', label: 'Gastar sem pensar' },
    ],
  },
  {
    id: 'din-002',
    category: 'Dinheiro',
    type: 'same',
    text: 'Vale mais a pena gastar com:',
    options: [
      { id: 'experiencia', emoji: '🎟', label: 'Experiência' },
      { id: 'coisa', emoji: '📦', label: 'Coisas' },
      { id: 'casa', emoji: '🛋', label: 'Casa' },
      { id: 'comida', emoji: '🍽', label: 'Comida boa' },
    ],
  },
  {
    id: 'din-003',
    category: 'Dinheiro',
    type: 'same',
    text: 'Numa promoção boa de passagem, vocês:',
    options: [
      { id: 'compra', emoji: '⚡', label: 'Compram na hora' },
      { id: 'pensa', emoji: '🤔', label: 'Pensam alguns dias' },
      { id: 'passa', emoji: '🙅', label: 'Deixam passar' },
    ],
  },
  { id: 'din-004', category: 'Dinheiro', type: 'who', text: 'Quem controla mais as contas?' },
  { id: 'din-005', category: 'Dinheiro', type: 'who', text: 'Quem gasta mais em coisa besta?' },
  { id: 'din-006', category: 'Dinheiro', type: 'who', text: 'Quem pesquisa preço antes de comprar?' },
  { id: 'din-007', category: 'Dinheiro', type: 'who', text: 'Quem convence o outro a gastar?' },
  { id: 'din-008', category: 'Dinheiro', type: 'who', text: 'Quem esquece de pagar alguma coisa no prazo?' },
  { id: 'din-009', category: 'Dinheiro', type: 'scale', text: 'De 1 a 5, quanto vocês são de guardar dinheiro?', scale: { low: 'nada', high: 'sempre' } },
  { id: 'din-010', category: 'Dinheiro', type: 'scale', text: 'De 1 a 5, quanto vocês gastam com delivery?', scale: { low: 'quase nunca', high: 'toda semana' } },
  {
    id: 'din-011',
    category: 'Dinheiro',
    type: 'know',
    text: 'Você prefere um presente caro ou vários pequenos?',
    predictText: '{nome} prefere um presente caro ou vários pequenos?',
    options: [
      { id: 'caro', emoji: '🎁', label: 'Um caro' },
      { id: 'varios', emoji: '🎈', label: 'Vários pequenos' },
    ],
  },
  {
    id: 'din-012',
    category: 'Dinheiro',
    type: 'know',
    text: 'Com um dia de folga e cem reais, você faria o quê?',
    predictText: 'Com um dia de folga e cem reais, o que {nome} faria?',
    options: [
      { id: 'comer', emoji: '🍽', label: 'Comer bem' },
      { id: 'passear', emoji: '🚗', label: 'Passear' },
      { id: 'comprar', emoji: '🛍', label: 'Comprar algo' },
      { id: 'guardar', emoji: '💰', label: 'Guardar' },
    ],
  },

  /* ────────────────────────────────────────────────────────── 🌱 Futuro ── */
  {
    id: 'fut-001',
    category: 'Futuro',
    type: 'same',
    text: 'O próximo plano de vocês é:',
    options: [
      { id: 'casa', emoji: '🏠', label: 'Casa' },
      { id: 'viagem', emoji: '✈️', label: 'Viagem' },
      { id: 'carreira', emoji: '💼', label: 'Carreira' },
      { id: 'guardar', emoji: '💰', label: 'Juntar dinheiro' },
    ],
  },
  {
    id: 'fut-002',
    category: 'Futuro',
    type: 'same',
    text: 'Daqui a cinco anos, vocês se imaginam:',
    options: [
      { id: 'mesma', emoji: '📍', label: 'Na mesma cidade' },
      { id: 'outra', emoji: '🗺', label: 'Em outra cidade' },
      { id: 'fora', emoji: '🌍', label: 'Em outro país' },
      { id: 'sei', emoji: '🤷', label: 'Sem ideia nenhuma' },
    ],
  },
  {
    id: 'fut-003',
    category: 'Futuro',
    type: 'same',
    text: 'A casa dos sonhos de vocês fica:',
    options: [
      { id: 'praia', emoji: '🌊', label: 'Perto da praia' },
      { id: 'campo', emoji: '🌳', label: 'No campo' },
      { id: 'cidade', emoji: '🏙', label: 'No meio da cidade' },
      { id: 'tanto', emoji: '🤝', label: 'Tanto faz, se for com o outro' },
    ],
  },
  {
    id: 'fut-004',
    category: 'Futuro',
    type: 'same',
    text: 'Se pudessem largar tudo por um ano, vocês:',
    options: [
      { id: 'viajar', emoji: '🎒', label: 'Viajariam' },
      { id: 'estudar', emoji: '📚', label: 'Estudariam algo novo' },
      { id: 'negocio', emoji: '🚀', label: 'Abririam um negócio' },
      { id: 'descansar', emoji: '😌', label: 'Descansariam' },
    ],
  },
  {
    id: 'fut-005',
    category: 'Futuro',
    type: 'same',
    text: 'O que vocês querem ter em casa um dia:',
    options: [
      { id: 'cachorro', emoji: '🐶', label: 'Um cachorro' },
      { id: 'quintal', emoji: '🌿', label: 'Um quintal' },
      { id: 'escritorio', emoji: '🖥', label: 'Um espaço para trabalhar' },
      { id: 'churrasqueira', emoji: '🔥', label: 'Uma churrasqueira' },
    ],
  },
  { id: 'fut-006', category: 'Futuro', type: 'who', text: 'Quem faz mais planos para o futuro?' },
  { id: 'fut-007', category: 'Futuro', type: 'who', text: 'Quem é mais ansioso para as coisas acontecerem?' },
  { id: 'fut-008', category: 'Futuro', type: 'who', text: 'Quem puxa o outro para fora da zona de conforto?' },
  { id: 'fut-009', category: 'Futuro', type: 'who', text: 'Quem seria o primeiro a topar mudar de cidade?' },
  { id: 'fut-010', category: 'Futuro', type: 'scale', text: 'De 1 a 5, quanto vocês gostam de mudança?', scale: { low: 'preferimos tudo igual', high: 'adoramos' } },
  { id: 'fut-011', category: 'Futuro', type: 'scale', text: 'De 1 a 5, quanto vocês conversam sobre o futuro?', scale: { low: 'quase nunca', high: 'toda semana' } },
  {
    id: 'fut-012',
    category: 'Futuro',
    type: 'know',
    text: 'O que você mais quer conquistar nos próximos anos?',
    predictText: 'O que {nome} mais quer conquistar nos próximos anos?',
    options: [
      { id: 'trabalho', emoji: '💼', label: 'Algo no trabalho' },
      { id: 'casa', emoji: '🏠', label: 'Um lugar para chamar de seu' },
      { id: 'viagem', emoji: '🌍', label: 'Conhecer o mundo' },
      { id: 'tempo', emoji: '⏳', label: 'Mais tempo livre' },
    ],
  },
  {
    id: 'fut-013',
    category: 'Futuro',
    type: 'know',
    text: 'Você prefere estabilidade ou novidade?',
    predictText: '{nome} prefere estabilidade ou novidade?',
    options: [
      { id: 'estabilidade', emoji: '⚓', label: 'Estabilidade' },
      { id: 'novidade', emoji: '🎢', label: 'Novidade' },
    ],
  },
  { id: 'fut-014', category: 'Futuro', type: 'who', text: 'Quem costuma ter a ideia maluca que o outro compra?' },

  /* ──────────────────────────────────────────────── 🔥 Casal (opt-in) ── */
  { id: 'cas-001', category: 'Casal', type: 'who', text: 'Quem flerta melhor?' },
  { id: 'cas-002', category: 'Casal', type: 'who', text: 'Quem manda a primeira mensagem quando fica de mal?' },
  { id: 'cas-003', category: 'Casal', type: 'who', text: 'Quem é mais grudento?' },
  { id: 'cas-004', category: 'Casal', type: 'who', text: 'Quem dá o melhor abraço?' },
  { id: 'cas-005', category: 'Casal', type: 'who', text: 'Quem puxa mais assunto quando os dois estão quietos?' },
  { id: 'cas-006', category: 'Casal', type: 'who', text: 'Quem é mais corajoso para se declarar em público?' },
  {
    id: 'cas-007',
    category: 'Casal',
    type: 'same',
    text: 'O date perfeito de vocês seria:',
    options: [
      { id: 'jantar', emoji: '🍽', label: 'Jantar' },
      { id: 'cinema', emoji: '🎬', label: 'Cinema' },
      { id: 'viagem', emoji: '✈️', label: 'Viagem' },
      { id: 'casa', emoji: '🏠', label: 'Noite em casa' },
      { id: 'festa', emoji: '🎉', label: 'Festa' },
    ],
  },
  {
    id: 'cas-008',
    category: 'Casal',
    type: 'same',
    text: 'O que vocês fariam numa noite só de vocês dois, sem celular?',
    options: [
      { id: 'conversar', emoji: '💬', label: 'Conversar até tarde' },
      { id: 'cozinhar', emoji: '🍳', label: 'Cozinhar' },
      { id: 'dancar', emoji: '💃', label: 'Colocar música e dançar' },
      { id: 'jogo', emoji: '🎲', label: 'Jogar alguma coisa' },
    ],
  },
  { id: 'cas-009', category: 'Casal', type: 'scale', text: 'De 1 a 5, quanto vocês são de mandar mensagem no meio do dia?', scale: { low: 'quase nunca', high: 'o dia todo' } },
  { id: 'cas-010', category: 'Casal', type: 'scale', text: 'De 1 a 5, quanto vocês curtem uma reconciliação depois da briga?', scale: { low: 'nem lembramos', high: 'vale a briga' } },
  {
    id: 'cas-011',
    category: 'Casal',
    type: 'know',
    text: 'O que mais te conquista no outro?',
    predictText: 'O que mais conquista {nome} no outro?',
    options: [
      { id: 'humor', emoji: '😂', label: 'O humor' },
      { id: 'cuidado', emoji: '🫶', label: 'O cuidado' },
      { id: 'jeito', emoji: '😍', label: 'O jeito' },
      { id: 'cabeca', emoji: '🧠', label: 'A cabeça' },
    ],
  },
  {
    id: 'cas-012',
    category: 'Casal',
    type: 'know',
    text: 'Qual elogio te deixa sem graça?',
    predictText: 'Qual elogio deixa {nome} sem graça?',
    options: [
      { id: 'bonito', emoji: '😊', label: 'Sobre a aparência' },
      { id: 'inteligente', emoji: '🧠', label: 'Sobre ser inteligente' },
      { id: 'engracado', emoji: '😂', label: 'Sobre ser engraçado' },
      { id: 'bom', emoji: '🫶', label: 'Sobre ser uma boa pessoa' },
    ],
  },
  { id: 'cas-013', category: 'Casal', type: 'who', text: 'Quem faria uma surpresa mais exagerada?' },
  { id: 'cas-014', category: 'Casal', type: 'who', text: 'Quem topa mais facilmente um plano de última hora do outro?' },
];
