import type { SecretMission } from './secret-types';

/**
 * Banco de missões do "Desafio Secreto" — cada pessoa recebe uma missão no
 * próprio celular e tenta cumpri-la sem o grupo perceber.
 *
 * A régua: a missão é boa se, quando revelada no fim, fizer o grupo gritar
 * "era por isso que você estava fazendo aquilo?!". Por isso nenhuma missão
 * pode acontecer sozinha (rir, conversar, comer) nem ser impossível de forçar
 * (chorar de emoção): ela exige que o jogador crie a situação e esconda a
 * intenção.
 *
 * Segurança — o alvo é manipulado sem saber, então ele precisa rir junto ao
 * descobrir. Nada de risco, álcool, direção, coisa alheia, celular de outra
 * pessoa, contato físico, paquera, dinheiro, vergonha, susto, mentira sobre
 * emergência, saúde, corpo, dieta, religião, política ou segredo de ninguém.
 * Só entra gente que está jogando: nunca garçom, entregador, vizinho ou
 * desconhecido.
 *
 * Contextos: a maioria das missões é de conversa, e conversa acontece em
 * qualquer lugar — essas listam os seis. Mas um seletor de lugar que não muda
 * nada é pior do que não existir, então a última seção é de missões que só
 * fazem sentido onde o grupo está: churrasco tem carne e fogo, viagem tem
 * chegada e mala, noite de jogos tem regra e placar. É o que faz o host sentir
 * diferença ao escolher. Nenhuma missão pressupõe objeto ou espaço que o grupo
 * não informou.
 */
export const MISSIONS: SecretMission[] = [
  // ─── Fala — arrancar uma palavra ou um assunto da boca do outro ────────────
  {
    id: 'fal-001',
    category: 'Fala',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém dizer a palavra "óbvio".',
  },
  {
    id: 'fal-002',
    category: 'Fala',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém responder "depende" para uma pergunta sua.',
  },
  {
    id: 'fal-003',
    category: 'Fala',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém falar do trabalho por um minuto sem parar.',
  },
  {
    id: 'fal-004',
    category: 'Fala',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém dizer o nome de uma cidade que nunca visitou.',
  },
  {
    id: 'fal-005',
    category: 'Fala',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém dizer "não acredito".',
  },
  {
    id: 'fal-006',
    category: 'Fala',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém dizer o nome de um professor que teve na escola.',
  },
  {
    id: 'fal-007',
    category: 'Fala',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém dizer o nome de um desenho que assistia quando era criança.',
  },
  {
    id: 'fal-008',
    category: 'Fala',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém falar de um filme que assistiu nos últimos meses.',
  },
  {
    id: 'fal-009',
    category: 'Fala',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém dizer "eu também".',
  },
  {
    id: 'fal-010',
    category: 'Fala',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém dizer o nome de uma comida que não suporta.',
  },
  {
    id: 'fal-011',
    category: 'Fala',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém cantar um pedaço de uma música.',
  },
  {
    id: 'fal-012',
    category: 'Fala',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém usar a palavra "saudade" numa frase.',
  },
  {
    id: 'fal-013',
    category: 'Fala',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém contar uma história da época de escola.',
  },
  {
    id: 'fal-014',
    category: 'Fala',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém falar uma frase em outro idioma.',
  },
  {
    id: 'fal-015',
    category: 'Fala',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém dizer o nome completo de outra pessoa que está aqui.',
  },
  {
    id: 'fal-016',
    category: 'Fala',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém dizer "eu não sabia disso".',
  },
  {
    id: 'fal-017',
    category: 'Fala',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém contar como conheceu outra pessoa do grupo.',
  },
  {
    id: 'fal-018',
    category: 'Fala',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém explicar a regra de um esporte.',
  },
  {
    id: 'fal-019',
    category: 'Fala',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém dizer "que absurdo".',
  },
  {
    id: 'fal-020',
    category: 'Fala',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Convença alguém a contar o final de um filme em voz alta.',
  },
  {
    id: 'fal-021',
    category: 'Fala',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém usar a palavra "jamais".',
  },
  {
    id: 'fal-022',
    category: 'Fala',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém contar um sonho que teve dormindo.',
  },
  {
    id: 'fal-023',
    category: 'Fala',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça três pessoas diferentes falarem o nome do mesmo filme.',
  },
  {
    id: 'fal-024',
    category: 'Fala',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém repetir a mesma frase duas vezes na mesma conversa.',
  },
  {
    id: 'fal-025',
    category: 'Fala',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Consiga que duas pessoas digam "com certeza" na mesma conversa.',
  },
  {
    id: 'fal-026',
    category: 'Fala',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém contar a mesma história para duas pessoas diferentes.',
  },
  // ─── Interação — fazer o outro entregar, mostrar ou se mexer ───────────────
  {
    id: 'int-001',
    category: 'Interação',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te mostrar uma foto no celular.',
  },
  {
    id: 'int-002',
    category: 'Interação',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'churrasco'],
    text: 'Faça alguém te passar um guardanapo.',
  },
  {
    id: 'int-003',
    category: 'Interação',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém checar a previsão do tempo.',
  },
  {
    id: 'int-004',
    category: 'Interação',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te dizer que horas são.',
  },
  {
    id: 'int-005',
    category: 'Interação',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém pesquisar algo na internet para te responder.',
  },
  {
    id: 'int-006',
    category: 'Interação',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te ajudar a lembrar o nome de uma coisa.',
  },
  {
    id: 'int-007',
    category: 'Interação',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém se levantar do lugar onde está.',
  },
  {
    id: 'int-008',
    category: 'Interação',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te mostrar um vídeo curto.',
  },
  {
    id: 'int-009',
    category: 'Interação',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te mostrar uma foto de um animal.',
  },
  {
    id: 'int-010',
    category: 'Interação',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'churrasco'],
    text: 'Faça alguém te oferecer um pedaço do que está comendo.',
  },
  {
    id: 'int-011',
    category: 'Interação',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém segurar o seu celular por alguns segundos.',
  },
  {
    id: 'int-012',
    category: 'Interação',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém abrir o mapa no celular.',
  },
  {
    id: 'int-013',
    category: 'Interação',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém trocar de lugar com você.',
  },
  {
    id: 'int-014',
    category: 'Interação',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te mostrar uma foto de quando era criança.',
  },
  {
    id: 'int-015',
    category: 'Interação',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém desenhar alguma coisa para você.',
  },
  {
    id: 'int-016',
    category: 'Interação',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te mostrar como faz alguma coisa com as mãos.',
  },
  {
    id: 'int-017',
    category: 'Interação',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém digitar alguma coisa no seu celular.',
  },
  {
    id: 'int-018',
    category: 'Interação',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te mandar uma mensagem estando do seu lado.',
  },
  {
    id: 'int-019',
    category: 'Interação',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém tirar uma foto de você.',
  },
  {
    id: 'int-020',
    category: 'Interação',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém guardar uma coisa sua por alguns minutos.',
  },
  {
    id: 'int-021',
    category: 'Interação',
    difficulty: 'media',
    contexts: ['casa', 'jantar', 'churrasco'],
    text: 'Faça alguém te explicar como se prepara algo que está na mesa.',
  },
  {
    id: 'int-022',
    category: 'Interação',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas te entregarem a mesma coisa, uma depois da outra.',
  },
  {
    id: 'int-023',
    category: 'Interação',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas trocarem de lugar entre elas.',
  },
  {
    id: 'int-024',
    category: 'Interação',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te mostrar três fotos diferentes no celular.',
  },
  // ─── Grupo — duas ou três pessoas na mesma jogada ──────────────────────────
  {
    id: 'gru-001',
    category: 'Grupo',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas olharem para a mesma coisa ao mesmo tempo.',
  },
  {
    id: 'gru-002',
    category: 'Grupo',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas responderem a mesma pergunta sua.',
  },
  {
    id: 'gru-003',
    category: 'Grupo',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas discutirem qual é o melhor sabor de pizza.',
  },
  {
    id: 'gru-004',
    category: 'Grupo',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas concordarem com você em voz alta.',
  },
  {
    id: 'gru-005',
    category: 'Grupo',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas cantarem a mesma música.',
  },
  {
    id: 'gru-006',
    category: 'Grupo',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas contarem versões diferentes da mesma história.',
  },
  {
    id: 'gru-007',
    category: 'Grupo',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça o grupo inteiro ficar em silêncio por alguns segundos.',
  },
  {
    id: 'gru-008',
    category: 'Grupo',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas disputarem quem lembra melhor de um detalhe.',
  },
  {
    id: 'gru-009',
    category: 'Grupo',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça três pessoas rirem da mesma história.',
  },
  {
    id: 'gru-010',
    category: 'Grupo',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas votarem em algo levantando a mão.',
  },
  {
    id: 'gru-011',
    category: 'Grupo',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça três pessoas diferentes dizerem a mesma palavra.',
  },
  {
    id: 'gru-012',
    category: 'Grupo',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça três pessoas contarem uma história de viagem cada uma.',
  },
  {
    id: 'gru-013',
    category: 'Grupo',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça três pessoas falarem do mesmo assunto em momentos separados.',
  },
  {
    id: 'gru-014',
    category: 'Grupo',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas começarem uma competição de quem faz algo melhor.',
  },
  {
    id: 'gru-015',
    category: 'Grupo',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Consiga que três pessoas diferentes repitam uma frase sua.',
  },
  {
    id: 'gru-016',
    category: 'Grupo',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça o grupo inteiro responder uma pergunta sua, um por um.',
  },
  {
    id: 'gru-017',
    category: 'Grupo',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas defenderem lados opostos de uma discussão boba.',
  },
  {
    id: 'gru-018',
    category: 'Grupo',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça três pessoas diferentes mostrarem alguma coisa no celular.',
  },
  // ─── Engraçado — imitação, história e talento inútil ───────────────────────
  {
    id: 'eng-001',
    category: 'Engraçado',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém contar uma história engraçada da infância.',
  },
  {
    id: 'eng-002',
    category: 'Engraçado',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém fazer uma careta.',
  },
  {
    id: 'eng-003',
    category: 'Engraçado',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém imitar o som de um animal.',
  },
  {
    id: 'eng-004',
    category: 'Engraçado',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém contar uma piada.',
  },
  {
    id: 'eng-005',
    category: 'Engraçado',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém falar com um sotaque diferente do normal.',
  },
  {
    id: 'eng-006',
    category: 'Engraçado',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém mostrar um talento inútil.',
  },
  {
    id: 'eng-007',
    category: 'Engraçado',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém imitar um personagem de filme.',
  },
  {
    id: 'eng-008',
    category: 'Engraçado',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém dançar por alguns segundos.',
  },
  {
    id: 'eng-009',
    category: 'Engraçado',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém contar uma história que termine com todos rindo.',
  },
  {
    id: 'eng-010',
    category: 'Engraçado',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém contar uma história que ninguém do grupo conhecia.',
  },
  {
    id: 'eng-011',
    category: 'Engraçado',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém rir tanto que precise parar de falar.',
  },
  {
    id: 'eng-012',
    category: 'Engraçado',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém inventar uma história absurda na hora.',
  },
  {
    id: 'eng-013',
    category: 'Engraçado',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém tentar falar um trava-língua.',
  },
  {
    id: 'eng-014',
    category: 'Engraçado',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém assobiar.',
  },
  {
    id: 'eng-015',
    category: 'Engraçado',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém imitar alguém famoso.',
  },
  {
    id: 'eng-016',
    category: 'Engraçado',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém fazer som de bateria com a boca.',
  },
  {
    id: 'eng-017',
    category: 'Engraçado',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém contar uma história de um bicho de estimação.',
  },
  {
    id: 'eng-018',
    category: 'Engraçado',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém tentar adivinhar uma música pelo ritmo.',
  },
  {
    id: 'eng-019',
    category: 'Engraçado',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém falar sem parar de um assunto que essa pessoa ama.',
  },
  {
    id: 'eng-020',
    category: 'Engraçado',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém contar um apelido engraçado que já teve.',
  },
  {
    id: 'eng-021',
    category: 'Engraçado',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas imitarem a mesma coisa, uma depois da outra.',
  },
  {
    id: 'eng-022',
    category: 'Engraçado',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça três pessoas contarem uma história engraçada cada uma.',
  },
  // ─── Social — virar o centro da conversa sem pedir ─────────────────────────
  {
    id: 'soc-001',
    category: 'Social',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém pedir sua opinião sobre alguma coisa.',
  },
  {
    id: 'soc-002',
    category: 'Social',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te recomendar uma série.',
  },
  {
    id: 'soc-003',
    category: 'Social',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te recomendar um lugar para conhecer.',
  },
  {
    id: 'soc-004',
    category: 'Social',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te perguntar como foi seu dia.',
  },
  {
    id: 'soc-005',
    category: 'Social',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te agradecer por alguma coisa.',
  },
  {
    id: 'soc-006',
    category: 'Social',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te contar um plano para os próximos meses.',
  },
  {
    id: 'soc-007',
    category: 'Social',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te recomendar uma música.',
  },
  {
    id: 'soc-008',
    category: 'Social',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te pedir uma dica sobre alguma coisa.',
  },
  {
    id: 'soc-009',
    category: 'Social',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te recomendar um livro ou um podcast.',
  },
  {
    id: 'soc-010',
    category: 'Social',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Convença alguém a mudar de ideia sobre uma bobagem.',
  },
  {
    id: 'soc-011',
    category: 'Social',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém elogiar alguma coisa que você disse.',
  },
  {
    id: 'soc-012',
    category: 'Social',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém te pedir um conselho.',
  },
  {
    id: 'soc-013',
    category: 'Social',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém concordar com uma opinião que você mesmo acha estranha.',
  },
  {
    id: 'soc-014',
    category: 'Social',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém defender você numa discussão boba.',
  },
  {
    id: 'soc-015',
    category: 'Social',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém prometer que vai assistir algo que você indicou.',
  },
  {
    id: 'soc-016',
    category: 'Social',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém admitir que estava errado sobre uma coisa pequena.',
  },
  {
    id: 'soc-017',
    category: 'Social',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém pedir sua ajuda para decidir alguma coisa.',
  },
  {
    id: 'soc-018',
    category: 'Social',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça três pessoas diferentes pedirem sua opinião na mesma noite.',
  },
  // ─── Discreta — ninguém percebe até a revelação ────────────────────────────
  {
    id: 'dis-001',
    category: 'Discreta',
    difficulty: 'facil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém dizer seu nome em voz alta.',
  },
  {
    id: 'dis-002',
    category: 'Discreta',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém repetir seu nome duas vezes na mesma conversa.',
  },
  {
    id: 'dis-003',
    category: 'Discreta',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém usar uma palavra que você disse antes.',
  },
  {
    id: 'dis-004',
    category: 'Discreta',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém bocejar.',
  },
  {
    id: 'dis-005',
    category: 'Discreta',
    difficulty: 'media',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém copiar a sua postura sem perceber.',
  },
  {
    id: 'dis-006',
    category: 'Discreta',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas diferentes te perguntarem a mesma coisa.',
  },
  {
    id: 'dis-007',
    category: 'Discreta',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém repetir uma ideia sua como se fosse dessa pessoa.',
  },
  {
    id: 'dis-008',
    category: 'Discreta',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça três pessoas diferentes dizerem seu nome durante a noite.',
  },
  {
    id: 'dis-009',
    category: 'Discreta',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém usar uma palavra que você inventou.',
  },
  {
    id: 'dis-010',
    category: 'Discreta',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas repetirem o mesmo gesto que você fez.',
  },
  {
    id: 'dis-011',
    category: 'Discreta',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça alguém terminar uma frase que você começou.',
  },
  {
    id: 'dis-012',
    category: 'Discreta',
    difficulty: 'dificil',
    contexts: ['casa', 'festa', 'jantar', 'viagem', 'churrasco', 'jogos'],
    text: 'Faça duas pessoas usarem a mesma palavra que você plantou na conversa.',
  },
  // ─── Do lugar — só existem onde o grupo está ───────────────────────────────
  {
    id: 'loc-001',
    category: 'Do lugar',
    difficulty: 'facil',
    contexts: ['churrasco'],
    text: 'Faça alguém opinar sobre o ponto da carne.',
  },
  {
    id: 'loc-002',
    category: 'Do lugar',
    difficulty: 'media',
    contexts: ['churrasco'],
    text: 'Faça alguém assumir a churrasqueira por alguns minutos.',
  },
  {
    id: 'loc-003',
    category: 'Do lugar',
    difficulty: 'media',
    contexts: ['churrasco'],
    text: 'Faça duas pessoas discordarem sobre a hora de tirar a carne.',
  },
  {
    id: 'loc-004',
    category: 'Do lugar',
    difficulty: 'dificil',
    contexts: ['churrasco'],
    text: 'Faça três pessoas diferentes darem palpite no fogo.',
  },
  {
    id: 'loc-005',
    category: 'Do lugar',
    difficulty: 'facil',
    contexts: ['viagem'],
    text: 'Faça alguém dizer quanto tempo falta para chegar.',
  },
  {
    id: 'loc-006',
    category: 'Do lugar',
    difficulty: 'media',
    contexts: ['viagem'],
    text: 'Faça alguém contar o que esqueceu de trazer.',
  },
  {
    id: 'loc-007',
    category: 'Do lugar',
    difficulty: 'media',
    contexts: ['viagem'],
    text: 'Faça alguém propor um lugar para ir amanhã.',
  },
  {
    id: 'loc-008',
    category: 'Do lugar',
    difficulty: 'dificil',
    contexts: ['viagem'],
    text: 'Faça duas pessoas discutirem o roteiro do dia seguinte.',
  },
  {
    id: 'loc-009',
    category: 'Do lugar',
    difficulty: 'facil',
    contexts: ['jogos'],
    text: 'Faça alguém explicar a regra de um jogo em voz alta.',
  },
  {
    id: 'loc-010',
    category: 'Do lugar',
    difficulty: 'media',
    contexts: ['jogos'],
    text: 'Faça alguém propor uma regra nova no meio da partida.',
  },
  {
    id: 'loc-011',
    category: 'Do lugar',
    difficulty: 'media',
    contexts: ['jogos'],
    text: 'Faça alguém conferir o placar em voz alta.',
  },
  {
    id: 'loc-012',
    category: 'Do lugar',
    difficulty: 'dificil',
    contexts: ['jogos'],
    text: 'Faça duas pessoas discutirem se uma jogada valeu.',
  },
  {
    id: 'loc-013',
    category: 'Do lugar',
    difficulty: 'facil',
    contexts: ['jantar'],
    text: 'Faça alguém elogiar um prato da mesa em voz alta.',
  },
  {
    id: 'loc-014',
    category: 'Do lugar',
    difficulty: 'media',
    contexts: ['jantar'],
    text: 'Faça alguém repetir o prato.',
  },
  {
    id: 'loc-015',
    category: 'Do lugar',
    difficulty: 'media',
    contexts: ['jantar', 'churrasco'],
    text: 'Faça alguém propor um brinde.',
  },
  {
    id: 'loc-016',
    category: 'Do lugar',
    difficulty: 'dificil',
    contexts: ['jantar'],
    text: 'Faça três pessoas diferentes falarem do mesmo prato.',
  },
  {
    id: 'loc-017',
    category: 'Do lugar',
    difficulty: 'facil',
    contexts: ['casa'],
    text: 'Faça alguém reclamar do que está tocando.',
  },
  {
    id: 'loc-018',
    category: 'Do lugar',
    difficulty: 'media',
    contexts: ['casa'],
    text: 'Faça alguém escolher a próxima música.',
  },
  {
    id: 'loc-019',
    category: 'Do lugar',
    difficulty: 'media',
    contexts: ['casa', 'jogos'],
    text: 'Faça alguém sugerir o que fazer depois disso.',
  },
  {
    id: 'loc-020',
    category: 'Do lugar',
    difficulty: 'dificil',
    contexts: ['casa'],
    text: 'Faça duas pessoas discutirem o que assistir.',
  },
  {
    id: 'loc-021',
    category: 'Do lugar',
    difficulty: 'facil',
    contexts: ['festa'],
    text: 'Faça alguém dizer que a música está alta.',
  },
  {
    id: 'loc-022',
    category: 'Do lugar',
    difficulty: 'media',
    contexts: ['festa'],
    text: 'Faça alguém tirar uma foto do grupo.',
  },
  {
    id: 'loc-023',
    category: 'Do lugar',
    difficulty: 'media',
    contexts: ['festa'],
    text: 'Faça alguém dizer a que horas pretende ir embora.',
  },
  {
    id: 'loc-024',
    category: 'Do lugar',
    difficulty: 'dificil',
    contexts: ['festa'],
    text: 'Faça três pessoas diferentes comentarem a mesma música.',
  },
];
